CREATE TABLE IF NOT EXISTS mst.working_day_calendar (
    working_day_calendar_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cust_id VARCHAR(10) NOT NULL,
    title VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    number_of_weeks INT NOT NULL,
    end_date DATE NOT NULL,
    default_holidays SMALLINT[] NULL,
    is_closed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NULL,
    updated_at TIMESTAMPTZ NULL,
    updated_by BIGINT NULL,
    closed_at TIMESTAMPTZ NULL,
    closed_by BIGINT NULL,
    closed_by_name VARCHAR(255) NULL,
    CONSTRAINT working_day_calendar_pkey PRIMARY KEY (working_day_calendar_id),
    CONSTRAINT fk_working_day_calendar_customer FOREIGN KEY (cust_id)
        REFERENCES smc.m_customer (cust_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT chk_working_day_calendar_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT chk_working_day_calendar_number_of_weeks CHECK (number_of_weeks BETWEEN 1 AND 99),
    CONSTRAINT chk_working_day_calendar_date_range CHECK (end_date >= start_date),
    CONSTRAINT chk_working_day_calendar_default_holidays CHECK (
        default_holidays IS NULL
        OR (
            array_length(default_holidays, 1) IS NOT NULL
            AND default_holidays <@ ARRAY[0, 1, 2, 3, 4, 5, 6]::SMALLINT[]
        )
    )
);

CREATE TABLE IF NOT EXISTS mst.working_day_calendar_holiday (
    working_day_calendar_holiday_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    working_day_calendar_id BIGINT NOT NULL,
    distributor_cust_id VARCHAR(10) NULL,
    holiday_date DATE NOT NULL,
    notes TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NULL,
    CONSTRAINT working_day_calendar_holiday_pkey PRIMARY KEY (working_day_calendar_holiday_id),
    CONSTRAINT fk_working_day_calendar_holiday_calendar FOREIGN KEY (working_day_calendar_id)
        REFERENCES mst.working_day_calendar (working_day_calendar_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT chk_working_day_calendar_holiday_notes_not_blank CHECK (btrim(notes) <> '')
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_working_day_calendar_holiday_date'
    ) THEN
        ALTER TABLE mst.working_day_calendar_holiday
            DROP CONSTRAINT uq_working_day_calendar_holiday_date;
    END IF;
END
$$;

ALTER TABLE mst.m_week
    ADD COLUMN IF NOT EXISTS working_day_calendar_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS calendar_week_no INT NULL;

ALTER TABLE mst.m_work_day
    ADD COLUMN IF NOT EXISTS working_day_calendar_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS holiday_source VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS holiday_note TEXT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_m_week_working_day_calendar'
    ) THEN
        ALTER TABLE mst.m_week
            ADD CONSTRAINT fk_m_week_working_day_calendar
            FOREIGN KEY (working_day_calendar_id)
            REFERENCES mst.working_day_calendar (working_day_calendar_id)
            ON UPDATE NO ACTION
            ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_m_week_calendar_week_no'
    ) THEN
        ALTER TABLE mst.m_week
            ADD CONSTRAINT chk_m_week_calendar_week_no
            CHECK (calendar_week_no IS NULL OR calendar_week_no > 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_m_work_day_working_day_calendar'
    ) THEN
        ALTER TABLE mst.m_work_day
            ADD CONSTRAINT fk_m_work_day_working_day_calendar
            FOREIGN KEY (working_day_calendar_id)
            REFERENCES mst.working_day_calendar (working_day_calendar_id)
            ON UPDATE NO ACTION
            ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_m_work_day_holiday_source'
    ) THEN
        ALTER TABLE mst.m_work_day
            ADD CONSTRAINT chk_m_work_day_holiday_source
            CHECK (
                holiday_source IS NULL
                OR holiday_source IN ('default', 'imported', 'default_imported')
            );
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_working_day_calendar_cust_date_range
    ON mst.working_day_calendar (cust_id, is_closed, start_date, end_date);

CREATE INDEX IF NOT EXISTS idx_working_day_calendar_latest
    ON mst.working_day_calendar (cust_id, end_date DESC)
    WHERE is_closed = false;

CREATE INDEX IF NOT EXISTS idx_working_day_calendar_holiday_calendar_date
    ON mst.working_day_calendar_holiday (working_day_calendar_id, distributor_cust_id, holiday_date);

CREATE UNIQUE INDEX IF NOT EXISTS ux_working_day_calendar_holiday_scope_date
    ON mst.working_day_calendar_holiday (working_day_calendar_id, COALESCE(distributor_cust_id, ''), holiday_date);

CREATE INDEX IF NOT EXISTS idx_m_week_working_day_calendar_week
    ON mst.m_week (working_day_calendar_id, week_id);

CREATE INDEX IF NOT EXISTS idx_m_week_working_day_calendar_calendar_week
    ON mst.m_week (working_day_calendar_id, calendar_week_no);

CREATE INDEX IF NOT EXISTS idx_m_work_day_working_day_calendar_date
    ON mst.m_work_day (working_day_calendar_id, work_date);

COMMENT ON TABLE mst.working_day_calendar IS 'Principal-owned Working Days Title setup. New calendars are append-only per principal to preserve legacy week numbering.';
COMMENT ON COLUMN mst.working_day_calendar.cust_id IS 'Principal customer id that owns the calendar setup.';
COMMENT ON COLUMN mst.working_day_calendar.default_holidays IS 'Weekday indexes treated as default holidays. Use 0=Sunday through 6=Saturday.';
COMMENT ON COLUMN mst.working_day_calendar_holiday.distributor_cust_id IS 'Nullable distributor customer id. NULL means principal/global holiday for the calendar; non-NULL means distributor-specific holiday override.';
COMMENT ON COLUMN mst.m_week.working_day_calendar_id IS 'Calendar setup that generated this week row. Nullable for legacy rows.';
COMMENT ON COLUMN mst.m_week.calendar_week_no IS 'Title-local week sequence starting from 1. Legacy week_id remains the compatible global week number.';
COMMENT ON COLUMN mst.m_work_day.working_day_calendar_id IS 'Calendar setup that generated this work-day row. Nullable for legacy rows.';
COMMENT ON COLUMN mst.m_work_day.holiday_source IS 'Generated holiday reason: default, imported, or default_imported.';
COMMENT ON COLUMN mst.m_work_day.holiday_note IS 'Imported holiday note denormalized for calendar rendering.';
