package entity

type CreateOrderDetBody struct {
	SeqNo                   int      `json:"seq_no"`
	ProId                   int      `json:"pro_id"`
	ItemType                int      `json:"item_type"`
	Qty                     *float64 `json:"qty"`
	QtyPo                   *float64 `json:"qty_po"`
	QtyPo1                  *float64 `json:"qty_po1"`
	QtyPo2                  *float64 `json:"qty_po2"`
	QtyPo3                  *float64 `json:"qty_po3"`
	QtyFinal                *float64 `json:"qty_final"`
	Qty1                    *float64 `json:"qty1"`
	Qty2                    *float64 `json:"qty2"`
	Qty3                    *float64 `json:"qty3"`
	Qty4                    *float64 `json:"qty4"`
	Qty5                    *float64 `json:"qty5"`
	Qty1Final               *float64 `json:"qty1_final"`
	Qty2Final               *float64 `json:"qty2_final"`
	Qty3Final               *float64 `json:"qty3_final"`
	Qty4Final               *float64 `json:"qty4_final"`
	Qty5Final               *float64 `json:"qty5_final"`
	Qty1Stok                *float64 `json:"qty1_stok"`
	Qty2Stok                *float64 `json:"qty2_stok"`
	Qty3Stok                *float64 `json:"qty3_stok"`
	PromoSo1                *float64 `json:"promo_so1"`
	PromoSo2                *float64 `json:"promo_so2"`
	PromoSo3                *float64 `json:"promo_so3"`
	PromoSo4                *float64 `json:"promo_so4"`
	PromoSo5                *float64 `json:"promo_so5"`
	PromoFinal1             *float64 `json:"promo_final1"`
	PromoFinal2             *float64 `json:"promo_final2"`
	PromoFinal3             *float64 `json:"promo_final3"`
	PromoFinal4             *float64 `json:"promo_final4"`
	PromoFinal5             *float64 `json:"promo_final5"`
	PromoPo1                *float64 `json:"promo_po1"`
	PromoPo2                *float64 `json:"promo_po2"`
	PromoPo3                *float64 `json:"promo_po3"`
	PromoPo4                *float64 `json:"promo_po4"`
	PromoPo5                *float64 `json:"promo_po5"`
	PromoRemarksSo          []string `json:"promo_remarks_so"`
	PromoRemarksFinal       []string `json:"promo_remarks_final"`
	PromoRemarksPo          []string `json:"promo_remarks_po"`
	IsProductPromotionSo    *bool    `json:"is_product_promotion_so"`
	IsProductPromotionFinal *bool    `json:"is_product_promotion_final"`
	IsProductPromotionPo    *bool    `json:"is_product_promotion_po"`
	// Qty4Stok       *float64 `json:"qty4_stok"`
	// Qty5Stok       *float64 `json:"qty5_stok"`
	PurchPrice1      *float64 `json:"purch_price1"`
	PurchPrice2      *float64 `json:"purch_price2"`
	PurchPrice3      *float64 `json:"purch_price3"`
	PurchPrice4      *float64 `json:"purch_price4"`
	PurchPrice5      *float64 `json:"purch_price5"`
	SellPrice1       *float64 `json:"sell_price1"`
	SellPrice2       *float64 `json:"sell_price2"`
	SellPrice3       *float64 `json:"sell_price3"`
	SellPrice4       *float64 `json:"sell_price4"`
	SellPrice5       *float64 `json:"sell_price5"`
	SellPriceSystem1 *float64 `json:"sell_price_system1"`
	SellPriceSystem2 *float64 `json:"sell_price_system2"`
	SellPriceSystem3 *float64 `json:"sell_price_system3"`
	SellPriceSystem4 *float64 `json:"sell_price_system4"`
	SellPriceSystem5 *float64 `json:"sell_price_system5"`
	Amount           *float64 `json:"amount"`
	AmountFinal      *float64 `json:"amount_final"`
	PromoValue       *float64 `json:"promo_value"`
	PromoValueFinal  *float64 `json:"promo_value_final"`
	DiscValue        *float64 `json:"disc_value"`
	DiscValueFinal   *float64 `json:"disc_value_final"`
	BatchNo          *string  `json:"batch_no"`
	ExpDate          *string  `json:"exp_date"`
	Vat              *float64 `json:"vat"`
	VatBg            *float64 `json:"vat_bg"`
	VatLgSell        *float64 `json:"vat_lg_sell"`
	VatValue         *float64 `json:"vat_value"`
	VatValueFinal    *float64 `json:"vat_value_final"`
	VatBgValue       *float64 `json:"vat_bg_value"`
	VatLgValue       *float64 `json:"vat_lg_value"`
	VatLgSellValue   *float64 `json:"vat_lg_sell_value"`
	DiscPo           *float64 `json:"disc_po"`
	VatValuePo       *float64 `json:"vat_value_po"`
	UnitId1          *string  `json:"unit_id1"`
	UnitId2          *string  `json:"unit_id2"`
	UnitId3          *string  `json:"unit_id3"`
	UnitId4          *string  `json:"unit_id4"`
	UnitId5          *string  `json:"unit_id5"`
	ConvUnit2        *int     `json:"conv_unit2"`
	ConvUnit3        *int     `json:"conv_unit3"`
	ConvUnit4        *int     `json:"conv_unit4"`
	ConvUnit5        *int     `json:"conv_unit5"`
	Notes            *string  `json:"notes"`
	DiscountID       *string  `json:"discount_id"`
	PromoID          *string  `json:"promo_id"`
}

type OrderDetResponse struct {
	OrderDetId              int64    `json:"order_detail_id"`
	SeqNo                   int      `json:"seq_no"`
	ProId                   int      `json:"pro_id"`
	ProCode                 string   `json:"pro_code"`
	ProName                 string   `json:"pro_name"`
	OrderStatus             string   `json:"order_status"`
	ItemType                int      `json:"item_type"`
	Promo1                  float64  `json:"promo1"`
	Promo2                  float64  `json:"promo2"`
	Promo3                  float64  `json:"promo3"`
	Promo4                  float64  `json:"promo4"`
	Promo5                  float64  `json:"promo5"`
	PromoTotal              float64  `json:"promo_total"`
	Remarks                 []string `json:"remarks"`
	IsProductPromotion      bool     `json:"is_product_promotion"`
	PromoSo1                float64  `json:"promo_so1"`
	PromoSo2                float64  `json:"promo_so2"`
	PromoSo3                float64  `json:"promo_so3"`
	PromoSo4                float64  `json:"promo_so4"`
	PromoSo5                float64  `json:"promo_so5"`
	PromoFinal1             float64  `json:"promo_final1"`
	PromoFinal2             float64  `json:"promo_final2"`
	PromoFinal3             float64  `json:"promo_final3"`
	PromoFinal4             float64  `json:"promo_final4"`
	PromoFinal5             float64  `json:"promo_final5"`
	PromoPo1                float64  `json:"promo_po1"`
	PromoPo2                float64  `json:"promo_po2"`
	PromoPo3                float64  `json:"promo_po3"`
	PromoPo4                float64  `json:"promo_po4"`
	PromoPo5                float64  `json:"promo_po5"`
	PromoRemarksSo          []string `json:"promo_remarks_so"`
	PromoRemarksFinal       []string `json:"promo_remarks_final"`
	PromoRemarksPo          []string `json:"promo_remarks_po"`
	IsProductPromotionSo    bool     `json:"is_product_promotion_so"`
	IsProductPromotionFinal bool     `json:"is_product_promotion_final"`
	IsProductPromotionPo    bool     `json:"is_product_promotion_po"`
	Qty                     *float64 `json:"qty"`
	QtyFinal                *float64 `json:"qty_final"`
	QtyPo                   *float64 `json:"qty_po"`
	OriginalQtyPo1          *float64 `json:"original_qty_po1"`
	OriginalQtyPo2          *float64 `json:"original_qty_po2"`
	OriginalQtyPo3          *float64 `json:"original_qty_po3"`
	QtyPo1                  *float64 `json:"qty_po1"`
	QtyPo2                  *float64 `json:"qty_po2"`
	QtyPo3                  *float64 `json:"qty_po3"`
	Qty1                    *float64 `json:"qty1"`
	Qty2                    *float64 `json:"qty2"`
	Qty3                    *float64 `json:"qty3"`
	Qty4                    *float64 `json:"qty4"`
	Qty5                    *float64 `json:"qty5"`
	Qty1Final               *float64 `json:"qty1_final"`
	Qty2Final               *float64 `json:"qty2_final"`
	Qty3Final               *float64 `json:"qty3_final"`
	Qty4Final               *float64 `json:"qty4_final"`
	Qty5Final               *float64 `json:"qty5_final"`
	Qty1Stok                *float64 `json:"qty1_stok"`
	Qty2Stok                *float64 `json:"qty2_stok"`
	Qty3Stok                *float64 `json:"qty3_stok"`
	// Qty4Stok       *float64 `json:"qty4_stok"`
	// Qty5Stok       *float64 `json:"qty5_stok"`
	PurchPrice1      *float64 `json:"purch_price1"`
	PurchPrice2      *float64 `json:"purch_price2"`
	PurchPrice3      *float64 `json:"purch_price3"`
	PurchPrice4      *float64 `json:"purch_price4"`
	PurchPrice5      *float64 `json:"purch_price5"`
	SellPrice1       *float64 `json:"sell_price1"`
	SellPrice2       *float64 `json:"sell_price2"`
	SellPrice3       *float64 `json:"sell_price3"`
	SellPrice4       *float64 `json:"sell_price4"`
	SellPrice5       *float64 `json:"sell_price5"`
	SellPricePo1     *float64 `json:"sell_price_po1"`
	SellPricePo2     *float64 `json:"sell_price_po2"`
	SellPricePo3     *float64 `json:"sell_price_po3"`
	SellPriceFinal1  *float64 `json:"sell_price_final1"`
	SellPriceFinal2  *float64 `json:"sell_price_final2"`
	SellPriceFinal3  *float64 `json:"sell_price_final3"`
	SellPriceSystem1 *float64 `json:"sell_price_system1"`
	SellPriceSystem2 *float64 `json:"sell_price_system2"`
	SellPriceSystem3 *float64 `json:"sell_price_system3"`
	SellPriceSystem4 *float64 `json:"sell_price_system4"`
	SellPriceSystem5 *float64 `json:"sell_price_system5"`
	Amount           *float64 `json:"amount"`
	AmountFinal      *float64 `json:"amount_final"`
	PromoValue       *float64 `json:"promo_value"`
	PromoValueFinal  *float64 `json:"promo_value_final"`
	DiscValue        *float64 `json:"disc_value"`
	DiscValueFinal   *float64 `json:"disc_value_final"`
	BatchNo          *string  `json:"batch_no"`
	ExpDate          *string  `json:"exp_date"`
	Vat              *float64 `json:"vat"`
	VatBg            *float64 `json:"vat_bg"`
	VatLgSell        *float64 `json:"vat_lg_sell"`
	VatValue         *float64 `json:"vat_value"`
	VatValueFinal    *float64 `json:"vat_value_final"`
	VatBgValue       *float64 `json:"vat_bg_value"`
	VatLgValue       *float64 `json:"vat_lg_value"`
	VatLgSellValue   *float64 `json:"vat_lg_sell_value"`
	DiscPo           *float64 `json:"disc_po"`
	VatValuePo       *float64 `json:"vat_value_po"`
	UnitId1          *string  `json:"unit_id1"`
	UnitId2          *string  `json:"unit_id2"`
	UnitId3          *string  `json:"unit_id3"`
	UnitId4          *string  `json:"unit_id4"`
	UnitId5          *string  `json:"unit_id5"`
	ConvUnit2        *int     `json:"conv_unit2"`
	ConvUnit3        *int     `json:"conv_unit3"`
	MpConvUnit2      *int     `json:"-"`
	MpConvUnit3      *int     `json:"-"`
	ConvUnit4        *int     `json:"conv_unit4"`
	ConvUnit5        *int     `json:"conv_unit5"`
	Notes            *string  `json:"notes"`
	DiscountID       *string  `json:"discount_id"`
	PromoID          *string  `json:"promoa_id"`
}

type UpdateOrderDetBody struct {
	SeqNo            int      `json:"seq_no"`
	OrderDetId       *int64   `json:"order_detail_id"`
	ProId            int      `json:"pro_id"`
	ItemType         int      `json:"item_type"`
	Qty              *float64 `json:"qty"`
	Qty1             *float64 `json:"qty1"`
	Qty2             *float64 `json:"qty2"`
	Qty3             *float64 `json:"qty3"`
	Qty4             *float64 `json:"qty4"`
	Qty5             *float64 `json:"qty5"`
	QtyFinal         *float64 `json:"qty_final"`
	Qty1Final        *float64 `json:"qty1_final"`
	Qty2Final        *float64 `json:"qty2_final"`
	Qty3Final        *float64 `json:"qty3_final"`
	Qty4Final        *float64 `json:"qty4_final"`
	Qty5Final        *float64 `json:"qty5_final"`
	Qty1Stok         *float64 `json:"qty1_stok"`
	Qty2Stok         *float64 `json:"qty2_stok"`
	Qty3Stok         *float64 `json:"qty3_stok"`
	QtyPo1           *float64 `json:"qty_po1"`
	QtyPo2           *float64 `json:"qty_po2"`
	QtyPo3           *float64 `json:"qty_po3"`
	PurchPrice1      *float64 `json:"purch_price1"`
	PurchPrice2      *float64 `json:"purch_price2"`
	PurchPrice3      *float64 `json:"purch_price3"`
	PurchPrice4      *float64 `json:"purch_price4"`
	PurchPrice5      *float64 `json:"purch_price5"`
	SellPrice1       *float64 `json:"sell_price1"`
	SellPrice2       *float64 `json:"sell_price2"`
	SellPrice3       *float64 `json:"sell_price3"`
	SellPrice4       *float64 `json:"sell_price4"`
	SellPrice5       *float64 `json:"sell_price5"`
	SellPricePo1     *float64 `json:"sell_price_po1"`
	SellPricePo2     *float64 `json:"sell_price_po2"`
	SellPricePo3     *float64 `json:"sell_price_po3"`
	SellPriceSystem1 *float64 `json:"sell_price_system1"`
	SellPriceSystem2 *float64 `json:"sell_price_system2"`
	SellPriceSystem3 *float64 `json:"sell_price_system3"`
	SellPriceSystem4 *float64 `json:"sell_price_system4"`
	SellPriceSystem5 *float64 `json:"sell_price_system5"`
	Amount           *float64 `json:"amount"`
	AmountFinal      *float64 `json:"amount_final"`
	PromoValue       *float64 `json:"promo_value"`
	PromoValueFinal  *float64 `json:"promo_value_final"`
	DiscValue        *float64 `json:"disc_value"`
	DiscValueFinal   *float64 `json:"disc_value_final"`
	BatchNo          *string  `json:"batch_no"`
	ExpDate          *string  `json:"exp_date"`
	Vat              *float64 `json:"vat"`
	VatBg            *float64 `json:"vat_bg"`
	VatLgSell        *float64 `json:"vat_lg_sell"`
	VatValue         *float64 `json:"vat_value"`
	VatValueFinal    *float64 `json:"vat_value_final"`
	VatBgValue       *float64 `json:"vat_bg_value"`
	VatLgValue       *float64 `json:"vat_lg_value"`
	VatLgSellValue   *float64 `json:"vat_lg_sell_value"`
	DiscPo           *float64 `json:"disc_po"`
	VatValuePo       *float64 `json:"vat_value_po"`
	UnitId1          *string  `json:"unit_id1"`
	UnitId2          *string  `json:"unit_id2"`
	UnitId3          *string  `json:"unit_id3"`
	UnitId4          *string  `json:"unit_id4"`
	UnitId5          *string  `json:"unit_id5"`
	ConvUnit2        *int     `json:"conv_unit2"`
	ConvUnit3        *int     `json:"conv_unit3"`
	ConvUnit4        *int     `json:"conv_unit4"`
	ConvUnit5        *int     `json:"conv_unit5"`
	Notes            *string  `json:"notes"`
	DiscountID       *string  `json:"discount_id"`
	PromoID          *string  `json:"promo_id"`
}

type UpdateFinalOrderDetBody struct {
	SeqNo            int      `json:"seq_no"`
	OrderDetId       *int64   `json:"order_detail_id"`
	ProId            int      `json:"pro_id"`
	ItemType         int      `json:"item_type"`
	Qty1             *float64 `json:"qty1"`
	Qty2             *float64 `json:"qty2"`
	Qty3             *float64 `json:"qty3"`
	Qty4             *float64 `json:"qty4"`
	Qty5             *float64 `json:"qty5"`
	QtyFinal         *float64 `json:"qty_final"`
	Qty1Final        *float64 `json:"qty1_final"`
	Qty2Final        *float64 `json:"qty2_final"`
	Qty3Final        *float64 `json:"qty3_final"`
	Qty4Final        *float64 `json:"qty4_final"`
	Qty5Final        *float64 `json:"qty5_final"`
	Qty1Stok         *float64 `json:"qty1_stok"`
	Qty2Stok         *float64 `json:"qty2_stok"`
	Qty3Stok         *float64 `json:"qty3_stok"`
	PurchPrice1      *float64 `json:"purch_price1"`
	PurchPrice2      *float64 `json:"purch_price2"`
	PurchPrice3      *float64 `json:"purch_price3"`
	PurchPrice4      *float64 `json:"purch_price4"`
	PurchPrice5      *float64 `json:"purch_price5"`
	SellPrice1       *float64 `json:"sell_price1"`
	SellPrice2       *float64 `json:"sell_price2"`
	SellPrice3       *float64 `json:"sell_price3"`
	SellPrice4       *float64 `json:"sell_price4"`
	SellPrice5       *float64 `json:"sell_price5"`
	SellPriceSystem1 *float64 `json:"sell_price_system1"`
	SellPriceSystem2 *float64 `json:"sell_price_system2"`
	SellPriceSystem3 *float64 `json:"sell_price_system3"`
	SellPriceSystem4 *float64 `json:"sell_price_system4"`
	SellPriceSystem5 *float64 `json:"sell_price_system5"`
	AmountFinal      *float64 `json:"amount_final"`
	PromoValueFinal  *float64 `json:"promo_value_final"`
	DiscValueFinal   *float64 `json:"disc_value_final"`
	BatchNo          *string  `json:"batch_no"`
	ExpDate          *string  `json:"exp_date"`
	Vat              *float64 `json:"vat"`
	VatBg            *float64 `json:"vat_bg"`
	VatLgSell        *float64 `json:"vat_lg_sell"`
	VatValueFinal    *float64 `json:"vat_value_final"`
	VatBgValue       *float64 `json:"vat_bg_value"`
	VatLgValue       *float64 `json:"vat_lg_value"`
	VatLgSellValue   *float64 `json:"vat_lg_sell_value"`
	DiscPo           *float64 `json:"disc_po"`
	VatValuePo       *float64 `json:"vat_value_po"`
	UnitId1          *string  `json:"unit_id1"`
	UnitId2          *string  `json:"unit_id2"`
	UnitId3          *string  `json:"unit_id3"`
	UnitId4          *string  `json:"unit_id4"`
	UnitId5          *string  `json:"unit_id5"`
	ConvUnit2        *int     `json:"conv_unit2"`
	ConvUnit3        *int     `json:"conv_unit3"`
	ConvUnit4        *int     `json:"conv_unit4"`
	ConvUnit5        *int     `json:"conv_unit5"`
	Notes            *string  `json:"notes"`
	DiscountID       *string  `json:"discount_id"`
	PromoID          *string  `json:"promo_id"`
}

type OrderDetWithGroup struct {
	Normal []CreateOrderDetBody `json:"normal"`
	Promo  []CreateOrderDetBody `json:"promo"`
}
type OrderRewardProductResponse struct {
	ProID      int     `json:"pro_id"`
	ProCode    string  `json:"pro_code"`
	ProName    string  `json:"pro_name"`
	UnitId1    *string `json:"unit_id1"`
	UnitId2    *string `json:"unit_id2"`
	UnitId3    *string `json:"unit_id3"`
	UnitId4    *string `json:"unit_id4"`
	UnitId5    *string `json:"unit_id5"`
	SellPrice1 float64 `json:"sell_price1"`
	SellPrice2 float64 `json:"sell_price2"`
	SellPrice3 float64 `json:"sell_price3"`
	Qty1       float64 `json:"qty1"`
	Qty2       float64 `json:"qty2"`
	Qty3       float64 `json:"qty3"`
	GrossValue float64 `json:"gross_value"`
	Promo1     float64 `json:"promo1"`
	Promo2     float64 `json:"promo2"`
	Promo3     float64 `json:"promo3"`
	Promo4     float64 `json:"promo4"`
	Promo5     float64 `json:"promo5"`
}

type OrderDetReadWithGroup struct {
	Normal            []OrderDetResponse           `json:"normal"`
	Promo             []OrderDetResponse           `json:"promo"`
	PromoRemarksSo    []string                     `json:"promo_remarks_so,omitempty"`
	PromoRemarksFinal []string                     `json:"promo_remarks_final,omitempty"`
	PromoRemarksPo    []string                     `json:"promo_remarks_po,omitempty"`
	FinalRemarks      []string                     `json:"final_remarks,omitempty"`
	RewardProducts    []OrderRewardProductResponse `json:"reward_products"`
}
type UpdateOrderDetWithGroup struct {
	Normal []UpdateOrderDetBody `json:"normal"`
	Promo  []CreateOrderDetBody `json:"promo"`
}

type UpdateFinalOrderDetWithGroup struct {
	Normal []UpdateFinalOrderDetBody `json:"normal"`
	Promo  []CreateOrderDetBody      `json:"promo"`
}

type ConsultDiscountOrderDetWithGroup struct {
	Normal []ConsultDiscountOrderDetBody `json:"normal"`
	Promo  []CreateOrderDetBody          `json:"promo"`
}

type ConsultDiscountOrderDetBody struct {
	ProId           int      `json:"pro_id"`
	Qty             *float64 `json:"qty"`
	Qty1            *float64 `json:"qty1"`
	Qty2            *float64 `json:"qty2"`
	Qty3            *float64 `json:"qty3"`
	Qty4            *float64 `json:"qty4"`
	Qty5            *float64 `json:"qty5"`
	Qty1Final       *float64 `json:"qty1_final"`
	Qty2Final       *float64 `json:"qty2_final"`
	Qty3Final       *float64 `json:"qty3_final"`
	Qty4Final       *float64 `json:"qty4_final"`
	Qty5Final       *float64 `json:"qty5_final"`
	SellPrice1      *float64 `json:"sell_price1"`
	SellPrice2      *float64 `json:"sell_price2"`
	SellPrice3      *float64 `json:"sell_price3"`
	SellPrice4      *float64 `json:"sell_price4"`
	SellPrice5      *float64 `json:"sell_price5"`
	Amount          *float64 `json:"amount"`
	AmountFinal     *float64 `json:"amount_final"`
	PromoValue      *float64 `json:"promo_value"`
	PromoValueFinal *float64 `json:"promo_value_final"`
	DiscValue       *float64 `json:"disc_value"`
	DiscValueFinal  *float64 `json:"disc_value_final"`
	Vat             *float64 `json:"vat"`
	VatValue        *float64 `json:"vat_value"`
	VatValueFinal   *float64 `json:"vat_value_final"`
	DiscPo          *float64 `json:"disc_po"`
	VatValuePo      *float64 `json:"vat_value_po"`
	DiscountID      *string  `json:"discount_id"`
}

type OrderDetReadRemarks struct {
	ReferenceId   string `gorm:"reference_id" json:"reference_id"`
	ReferenceType string `gorm:"reference_type" json:"reference_type"`
	Description   string `gorm:"description" json:"description"`
}
