package model

import "time"

type MOutlet struct {
	CustId                string     `json:"cust_id" db:"cust_id"`
	OutletId              int        `json:"outlet_id" db:"outlet_id"`
	SalesmanId            int        `json:"salesman_id" db:"salesman_id"`
	OutletCode            *string    `json:"outlet_code,omitempty" db:"outlet_code"`
	OutletPrincipalCode   *string    `json:"outlet_principal_code,omitempty" db:"outlet_principal_code"`
	Source                *int       `json:"source,omitempty" db:"source"`
	OutletName            *string    `json:"outlet_name,omitempty" db:"outlet_name"`
	Address               *string    `json:"address" db:"address1"`
	PhoneNo               *string    `json:"phone_no" db:"phone_no"`
	WaNo                  *string    `json:"wa_no" db:"wa_no"`
	FaxNo                 *string    `json:"fax_no" db:"fax_no"`
	BuldingOwn            *int       `json:"building_own" db:"building_own"`
	Latitude              *string    `json:"latitude" db:"latitude"`
	Longitude             *string    `json:"longitude" db:"longitude"`
	FileUrl               *string    `json:"file_url" db:"file_url"`
	IsActive              bool       `db:"is_active" json:"is_active"`
	IsDel                 bool       `db:"is_del" json:"is_del"`
	CreatedBy             *int64     `db:"created_by,omitempty" json:"created_by"`
	CreatedAt             *time.Time `db:"created_at,omitempty" json:"created_at"`
	UpdatedBy             *int64     `db:"updated_by,omitempty" json:"updated_by"`
	UpdatedByName         *string    `json:"updated_by_name" db:"updated_by_name"`
	UpdatedAt             *time.Time `db:"updated_at,omitempty" json:"updated_at"`
	DeletedBy             *int64     `db:"deleted_by,omitempty" json:"deleted_by"`
	DeletedAt             *time.Time `db:"deleted_at,omitempty" json:"deleted_at"`
	VerificationStatus    *int       `json:"verification_status" db:"verification_status"`
	OutletStatus          int        `json:"outlet_status" db:"outlet_status"`
	NonDiscountGroupID    int        `json:"non_discount_group_id" db:"non_discount_group_id"`
	NonOutletGroupID      int        `json:"non_outlet_group_id" db:"non_outlet_group_id"`
	NonPriceGroupID       int        `json:"non_price_group_id" db:"non_price_group_id"`
	NonOutletClassID      int        `json:"non_outlet_class_id" db:"non_outlet_class_id"`
	NonOutletTypeID       int        `json:"non_outlet_type_id" db:"non_outlet_type_id"`
	CreditLimitAction     int        `json:"credit_limit_action" db:"credit_limit_action"`
	CreditLimitActionName *string    `json:"credit_limit_action_name" db:"credit_limit_action_name"`
}

type MOutletFromList struct {
	CustId             string     `json:"cust_id" db:"cust_id"`
	OutletId           int        `json:"outlet_id" db:"outlet_id"`
	SalesmanId         int        `json:"salesman_id" db:"salesman_id"`
	OutletCode         *string    `json:"outlet_code,omitempty" db:"outlet_code"`
	OutletName         *string    `json:"outlet_name,omitempty" db:"outlet_name"`
	Address            *string    `json:"address" db:"outlet_address"`
	PhoneNo            *string    `json:"phone_no" db:"phone_no"`
	WaNo               *string    `json:"wa_no" db:"wa_no"`
	FaxNo              *string    `json:"fax_no" db:"fax_no"`
	BuldingOwn         *int       `json:"building_own" db:"building_own"`
	Latitude           *string    `json:"latitude" db:"latitude"`
	Longitude          *string    `json:"longitude" db:"longitude"`
	IsActive           bool       `db:"is_active" json:"is_active"`
	IsDel              bool       `db:"is_del" json:"is_del"`
	CreatedBy          *int64     `db:"created_by,omitempty" json:"created_by"`
	CreatedAt          *time.Time `db:"created_at,omitempty" json:"created_at"`
	UpdatedBy          *int64     `db:"updated_by,omitempty" json:"updated_by"`
	UpdatedByName      *string    `json:"updated_by_name" db:"updated_by_name"`
	UpdatedAt          *time.Time `db:"updated_at,omitempty" json:"updated_at"`
	DeletedBy          *int64     `db:"deleted_by,omitempty" json:"deleted_by"`
	DeletedAt          *time.Time `db:"deleted_at,omitempty" json:"deleted_at"`
	VerificationStatus *int       `json:"verification_status" db:"verification_status"`
	RouteCode          *int       `json:"route_code" db:"route_code"`
	RouteName          *string    `json:"route_name" db:"route_name"`
	PjpId              *int       `json:"pjp_id" db:"pjp_id"`
	PjpCode            *int       `json:"pjp_code" db:"pjp_code"`
	OutletStatus       int64      `json:"outlet_status" db:"outlet_status"`
}

type MOutletRead struct {
	CustId             string     `json:"cust_id" db:"cust_id"`
	OutletId           int        `json:"outlet_id" db:"outlet_id"`
	SalesmanId         int        `json:"salesman_id" db:"salesman_id"`
	OutletName         *string    `json:"outlet_name,omitempty" db:"outlet_name"`
	Address            *string    `json:"address" db:"address1"`
	OutletStatus       int64      `json:"outlet_status" db:"outlet_status"`
	OutletCode         *string    `json:"outlet_code" db:"outlet_code"`
	PhoneNo            *string    `json:"phone_no" db:"phone_no"`
	WaNo               *string    `json:"wa_no" db:"wa_no"`
	FaxNo              *string    `json:"fax_no" db:"fax_no"`
	Email              *string    `json:"email" db:"email"`
	BuldingOwn         *int       `json:"building_own" db:"building_own"`
	Latitude           *string    `json:"latitude" db:"latitude"`
	Longitude          *string    `json:"longitude" db:"longitude"`
	IsActive           bool       `db:"is_active" json:"is_active"`
	IsDel              bool       `db:"is_del" json:"is_del"`
	CreatedBy          *int64     `db:"created_by,omitempty" json:"created_by"`
	CreatedAt          *time.Time `db:"created_at,omitempty" json:"created_at"`
	UpdatedBy          *int64     `db:"updated_by,omitempty" json:"updated_by"`
	UpdatedByName      *string    `json:"updated_by_name" db:"updated_by_name"`
	UpdatedAt          *time.Time `db:"updated_at,omitempty" json:"updated_at"`
	DeletedBy          *int64     `db:"deleted_by,omitempty" json:"deleted_by"`
	DeletedAt          *time.Time `db:"deleted_at,omitempty" json:"deleted_at"`
	VerificationStatus *int       `json:"verification_status" db:"verification_status"`
	VerifiedBy         *int64     `db:"verified_by,omitempty" json:"verified_by"`
	VerifiedByName     *string    `json:"verified_by_name" db:"verified_by_name"`
	VerifiedAt         *time.Time `db:"verified_at,omitempty" json:"verified_at"`
	Date               *time.Time `db:"date" json:"date"`
}

type MOutletReadFromList struct {
	CustID             string     `json:"cust_id" db:"cust_id"`
	OutletID           int        `json:"outlet_id" db:"outlet_id"`
	OutletCode         *string    `json:"outlet_code,omitempty" db:"outlet_code"`
	OutletName         *string    `json:"outlet_name,omitempty" db:"outlet_name"`
	Address            *string    `json:"address" db:"address1"`
	PhoneNo            *string    `json:"phone_no" db:"phone_no"`
	WaNo               *string    `json:"wa_no" db:"wa_no"`
	FaxNo              *string    `json:"fax_no" db:"fax_no"`
	BuldingOwn         *int       `json:"building_own" db:"building_own"`
	Latitude           *string    `json:"latitude" db:"latitude"`
	Longitude          *string    `json:"longitude" db:"longitude"`
	IsActive           bool       `db:"is_active" json:"is_active"`
	IsDel              bool       `db:"is_del" json:"is_del"`
	CreatedBy          *int64     `db:"created_by,omitempty" json:"created_by"`
	CreatedAt          *time.Time `db:"created_at,omitempty" json:"created_at"`
	UpdatedBy          *int64     `db:"updated_by,omitempty" json:"updated_by"`
	UpdatedByName      *string    `json:"updated_by_name" db:"updated_by_name"`
	UpdatedAt          *time.Time `db:"updated_at,omitempty" json:"updated_at"`
	DeletedBy          *int64     `db:"deleted_by,omitempty" json:"deleted_by"`
	DeletedAt          *time.Time `db:"deleted_at,omitempty" json:"deleted_at"`
	OutletStatus       *int       `json:"outlet_status" db:"outlet_status"`
	VerificationStatus *int       `json:"verification_status" db:"verification_status"`
}

type MOutletCreadFromList struct {
	Id              int        `json:"id" db:"id"`
	RouteCode       *int       `json:"route_code" db:"route_code"`
	RouteName       *string    `json:"route_name" db:"route_name"`
	OutletId        int        `json:"outlet_id" db:"outlet_id"`
	OutletCode      *string    `json:"outlet_code" db:"outlet_code"`
	OutletName      *string    `json:"outlet_name" db:"outlet_name"`
	Longitude       *string    `json:"longitude" db:"longitude"`
	Latitude        *string    `json:"latitude" db:"latitude"`
	OutletStatus    int        `json:"outlet_status" db:"outlet_status"`
	OutletAddress   *string    `json:"outlet_address" db:"outlet_address"`
	PjpId           *int       `json:"pjp_id" db:"pjp_id"`
	PjpCode         *int       `json:"pjp_code" db:"pjp_code"`
	CustId          string     `json:"cust_id" db:"cust_id"`
	Status          string     `json:"status" db:"status"`
	CreatedAt       *time.Time `json:"created_at" db:"created_at"`
	UpdatedAt       *time.Time `json:"updated_at" db:"updated_at"`
	VerifiedDate    *time.Time `json:"verified_date" db:"verified_date"`
	OldPjpId        *int       `json:"old_pjp_id" db:"old_pjp_id"`
	OldPjpCode      *int       `json:"old_pjp_code" db:"old_pjp_code"`
	OldRouteCode    *int       `json:"old_route_code" db:"old_route_code"`
	OldRouteName    *string    `json:"old_route_name" db:"old_route_name"`
	Photo           *string    `json:"photo" db:"photo"`
	AvgSalesWeek    *float64   `json:"avg_sales_week" db:"avg_sales_week"`
	IndexDay        *int       `json:"index_day" db:"index_day"`
	StartWeek       *string    `json:"start_week" db:"start_week"`
	IsInCurrentYear *bool      `json:"is_in_current_year" db:"is_in_current_year"`
	Week            *int       `json:"week" db:"week"`
	Year            *int       `json:"year" db:"year"`
	Date            *time.Time `json:"date" db:"date"`
	IsAdditional    *bool      `json:"is_additional" db:"is_additional"`
	IsExtraCall     *bool      `json:"is_extra_call" db:"is_extra_call"`
}

type OutletReads struct {
	CustId                string     `json:"cust_id" db:"cust_id"`
	OutletId              int        `json:"outlet_id" db:"outlet_id"`
	Source                *int       `json:"source,omitempty" db:"source"`
	OutletCode            *string    `json:"outlet_code,omitempty" db:"outlet_code"`
	OutletName            *string    `json:"outlet_name,omitempty" db:"outlet_name"`
	Barcode               *string    `json:"barcode" db:"barcode"`
	OutletStatus          *int       `json:"outlet_status" db:"outlet_status"`
	Address1              *string    `json:"address1" db:"address1"`
	Address2              *string    `json:"address2" db:"address2"`
	City                  *string    `json:"city" db:"city"`
	ZipCode               *string    `json:"zip_code" db:"zip_code"`
	PhoneNo               *string    `json:"phone_no" db:"phone_no"`
	WaNo                  *string    `json:"wa_no" db:"wa_no"`
	FaxNo                 *string    `json:"fax_no" db:"fax_no"`
	Email                 *string    `json:"email" db:"email"`
	DiscGrpId             *int       `json:"disc_grp_id" db:"disc_grp_id"`
	DiscGrpCode           *string    `json:"disc_grp_code" db:"disc_grp_code"`
	DiscGrpName           *string    `json:"disc_grp_name" db:"disc_grp_name"`
	OtLocId               *int       `json:"ot_loc_id" db:"ot_loc_id"`
	OtLocCode             *string    `json:"ot_loc_code" db:"ot_loc_code"`
	OtLocName             *string    `json:"ot_loc_name" db:"ot_loc_name"`
	OtGrpId               *int       `json:"ot_grp_id" db:"ot_grp_id"`
	OtGrpCode             *string    `json:"ot_grp_code" db:"ot_grp_code"`
	OtGrpName             *string    `json:"ot_grp_name" db:"ot_grp_name"`
	PriceGrpId            *int       `json:"price_grp_id" db:"price_grp_id"`
	PriceGrpCode          *string    `json:"price_grp_code" db:"price_grp_code"`
	PriceGrpName          *string    `json:"price_grp_name" db:"price_grp_name"`
	DistrictId            *int       `json:"district_id" db:"district_id"`
	DistrictCode          *string    `json:"district_code" db:"district_code"`
	DistrictName          *string    `json:"district_name" db:"district_name"`
	BeatId                *int       `json:"beat_id" db:"beat_id"`
	BeatCode              *string    `json:"beat_code" db:"beat_code"`
	BeatName              *string    `json:"beat_name" db:"beat_name"`
	SbeatId               *int       `json:"sbeat_id" db:"sbeat_id"`
	SBeatCode             *string    `json:"sbeat_code" db:"sbeat_code"`
	SBeatName             *string    `json:"sbeat_name" db:"sbeat_name"`
	OtClassId             *int       `json:"ot_class_id" db:"ot_class_id"`
	OtClassCode           *string    `json:"ot_class_code" db:"ot_class_code"`
	OtClassName           *string    `json:"ot_class_name" db:"ot_class_name"`
	IndustryId            *int       `json:"industry_id" db:"industry_id"`
	IndustryCode          *string    `json:"industry_code" db:"industry_code"`
	Industryname          *string    `json:"industry_name" db:"industry_name"`
	MarketId              *int       `json:"market_id" db:"market_id"`
	MarketCode            *string    `json:"market_code" db:"market_code"`
	MarketName            *string    `json:"market_name" db:"market_name"`
	Top                   *int       `json:"top" db:"top"`
	PaymentType           *int       `json:"payment_type" db:"payment_type"`
	PaymentTypeName       *string    `json:"payment_type_name" db:"payment_type_name"`
	IsContraBon           *bool      `json:"is_contra_bon" db:"is_contra_bon"`
	PluGrpId              *int       `json:"plu_grp_id" db:"plu_grp_id"`
	PluGrpCode            *string    `json:"plu_grp_code" db:"plu_grp_code"`
	PluGrpName            *string    `json:"plu_grp_name" db:"plu_grp_name"`
	ConvGrpId             *int       `json:"conv_grp_id" db:"conv_grp_id"`
	ConvGrpCode           *string    `json:"conv_grp_code" db:"conv_grp_code"`
	ConvGrpName           *string    `json:"conv_grp_name" db:"conv_grp_name"`
	DiscInvId             *int       `json:"disc_inv_id" db:"disc_inv_id"`
	DiscInvCode           *string    `json:"disc_inv_code" db:"disc_inv_code"`
	DiscInvName           *string    `json:"disc_inv_name" db:"disc_inv_name"`
	AgentFrom             *string    `json:"agent_from" db:"agent_from"`
	CreditLimitType       *int       `json:"credit_limit_type" db:"credit_limit_type"`
	CreditLimitTypeName   *string    `json:"credit_limit_type_name" db:"credit_limit_type_name"`
	CreditLimit           *float64   `json:"credit_limit" db:"credit_limit"`
	SalesInvLimitType     *int       `json:"sales_inv_limit_type" db:"sales_inv_limit_type"`
	SalesInvLimitTypeName *string    `json:"sales_inv_limit_type_name" db:"sales_inv_limit_type_name"`
	SalesInvLimit         *int       `json:"sales_inv_limit" db:"sales_inv_limit"`
	AvgSalesWeek          *float64   `json:"avg_sales_week" db:"avg_sales_week"`
	AvgSalesMonth         *float64   `json:"avg_sales_month" db:"avg_sales_month"`
	FirstTransDate        *string    `json:"first_trans_date" db:"first_trans_date"`
	LastTransDate         *string    `json:"last_trans_date" db:"last_trans_date"`
	FirstWeekNo           *int       `json:"first_week_no" db:"first_week_no"`
	OtStartDate           *string    `json:"ot_start_date" db:"ot_start_date"`
	OtRegDate             *string    `json:"ot_reg_date" db:"ot_reg_date"`
	BuldingOwn            *int       `json:"building_own" db:"building_own"`
	Dob                   *string    `json:"dob" db:"dob"`
	ArStatus              *int       `json:"ar_status" db:"ar_status"`
	ArTotal               *float64   `json:"ar_total" db:"ar_total"`
	CloseDate             *time.Time `json:"closed_date" db:"closed_date"`
	IsEmbBail             *bool      `json:"is_emb_bail" db:"is_emb_bail"`
	TaxName               *string    `json:"tax_name" db:"tax_name"`
	TaxAddr1              *string    `json:"tax_addr1" db:"tax_addr1"`
	TaxAddr2              *string    `json:"tax_addr2" db:"tax_addr2"`
	TaxCity               *string    `json:"tax_city" db:"tax_city"`
	TaxNo                 *string    `json:"tax_no" db:"tax_no"`
	TaxInvoiceForm        *int       `json:"tax_invoice_form" db:"tax_invoice_form"`
	OwnerName             *string    `json:"owner_name" db:"owner_name"`
	OwnerAdd1             *string    `json:"owner_addr1" db:"owner_addr1"`
	OwnerAddr2            *string    `json:"owner_addr2" db:"owner_addr2"`
	OwnerCity             *string    `json:"owner_city" db:"owner_city"`
	OwnerPhoneNo          *string    `json:"owner_phone_no" db:"owner_phone_no"`
	OwnerIdNo             *string    `json:"owner_id_no" db:"owner_id_no"`
	DelvAdd1              *string    `json:"delv_addr1" db:"delv_addr1"`
	DelvCity              *string    `json:"delv_city" db:"delv_city"`
	DelvLatitude          *string    `json:"delv_latitude" db:"delv_latitude"`
	DelvLongitude         *string    `json:"delv_longitude" db:"delv_longitude"`
	DelvAddr2             *string    `json:"delv_addr2" db:"delv_addr2"`
	DelvCity2             *string    `json:"delv_city2" db:"delv_city2"`
	DelvLatitude2         *string    `json:"delv_latitude2" db:"delv_latitude2"`
	DelvLongitude2        *string    `json:"delv_longitude2" db:"delv_longitude2"`
	InvAddr1              *string    `json:"inv_addr1" db:"inv_addr1"`
	InvAddr2              *string    `json:"inv_addr2" db:"inv_addr2"`
	InvCity               *string    `json:"inv_city" db:"inv_city"`
	Latitude              *string    `json:"latitude" db:"latitude"`
	Longitude             *string    `json:"longitude" db:"longitude"`
	ImageUrl              *string    `json:"image_url" db:"image_url"`
	IsActive              bool       `db:"is_active" json:"is_active"`
	IsDel                 bool       `db:"is_del" json:"is_del"`
	CreatedBy             *int64     `db:"created_by,omitempty" json:"created_by"`
	CreatedAt             *time.Time `db:"created_at,omitempty" json:"created_at"`
	UpdatedBy             *int64     `db:"updated_by,omitempty" json:"updated_by"`
	UpdatedByName         *string    `db:"updated_by_name" json:"updated_by_name"`
	UpdatedAt             *time.Time `db:"updated_at,omitempty" json:"updated_at"`
	DeletedBy             *int64     `db:"deleted_by,omitempty" json:"deleted_by"`
	DeletedAt             *time.Time `db:"deleted_at,omitempty" json:"deleted_at"`
	OtTypeId              *int       `db:"ot_type_id" json:"ot_type_id"`
	OtTypeCode            *string    `db:"ot_type_code" json:"ot_type_code"`
	OtTypeName            *string    `db:"ot_type_name" json:"ot_type_name"`
	IsObs                 *bool      `db:"is_obs" json:"is_obs"`
	Obs                   *int       `db:"obs" json:"obs"`

	OutletWardId            *string    `db:"outlet_ward_id" json:"outlet_ward_id"`
	OutletWard              *string    `db:"outlet_ward" json:"outlet_ward"`
	OutletSubDistrictId     *string    `db:"outlet_sub_district_id" json:"outlet_sub_district_id"`
	OutletSubDistrict       *string    `db:"outlet_sub_district" json:"outlet_sub_district"`
	OutletRegencyId         *string    `db:"outlet_regency_id" json:"outlet_regency_id"`
	OutletRegency           *string    `db:"outlet_regency" json:"outlet_regency"`
	OutletProvinceId        *string    `db:"outlet_province_id" json:"outlet_province_id"`
	OutletProvince          *string    `db:"outlet_province" json:"outlet_province"`
	IsWaNo                  *bool      `db:"is_wa_no" json:"is_wa_no"`
	DelvWardId              *string    `db:"delv_ward_id" json:"delv_ward_id"`
	DelvWard                *string    `db:"delv_ward" json:"delv_ward"`
	DelvSubDistrictId       *string    `db:"delv_sub_district_id" json:"delv_sub_district_id"`
	DelvSubDistrict         *string    `db:"delv_sub_district" json:"delv_sub_district"`
	DelvRegencyId           *string    `db:"delv_regency_id" json:"delv_regency_id"`
	DelvRegency             *string    `db:"delv_regency" json:"delv_regency"`
	DelvProvinceId          *string    `db:"delv_province_id" json:"delv_province_id"`
	DelvProvince            *string    `db:"delv_province" json:"delv_province"`
	DelvZipCode             *string    `db:"delv_zip_code" json:"delv_zip_code"`
	DelvIsSameAddress       *bool      `db:"delv_is_same_addr" json:"delv_is_same_addr"`
	DelvWardId2             *string    `db:"delv_ward_id2" json:"delv_ward_id2"`
	DelvWard2               *string    `db:"delv_ward2" json:"delv_ward2"`
	DelvSubDistrictId2      *string    `db:"delv_sub_district_id2" json:"delv_sub_district_id2"`
	DelvSubDistrict2        *string    `db:"delv_sub_district2" json:"delv_sub_district2"`
	DelvRegencyId2          *string    `db:"delv_regency_id2" json:"delv_regency_id2"`
	DelvRegency2            *string    `db:"delv_regency2" json:"delv_regency2"`
	DelvProvinceId2         *string    `db:"delv_province_id2" json:"delv_province_id2"`
	DelvProvince2           *string    `db:"delv_province2" json:"delv_province2"`
	DelvZipCode2            *string    `db:"delv_zip_code2" json:"delv_zip_code2"`
	InvWardId               *string    `db:"inv_ward_id" json:"inv_ward_id"`
	InvWard                 *string    `db:"inv_ward" json:"inv_ward"`
	InvSubDistrictId        *string    `db:"inv_sub_district_id" json:"inv_sub_district_id"`
	InvSubDistrict          *string    `db:"inv_sub_district" json:"inv_sub_district"`
	InvRegencyId            *string    `db:"inv_regency_id" json:"inv_regency_id"`
	InvRegency              *string    `db:"inv_regency" json:"inv_regency"`
	InvProvinceId           *string    `db:"inv_province_id" json:"inv_province_id"`
	InvProvince             *string    `db:"inv_province" json:"inv_province"`
	InvZipCode              *string    `db:"inv_zip_code" json:"inv_zip_code"`
	InvIsSameAddress        *bool      `db:"inv_is_same_addr" json:"inv_is_same_addr"`
	VerificationStatus      *int       `db:"verification_status" json:"verification_status"`
	VerifiedBy              *int64     `db:"verified_by,omitempty" json:"verified_by"`
	VerifiedByName          *string    `db:"verified_by_name" json:"verified_by_name"`
	VerifiedAt              *time.Time `db:"verified_at,omitempty" json:"verified_at"`
	ObsType                 *int       `db:"obs_type" json:"obs_type"`
	ObsTypeName             *string    `db:"obs_type_name" json:"obs_type_name"`
	CreditLimitAction       *int       `db:"credit_limit_action" json:"credit_limit_action"`
	CreditLimitActionName   *string    `db:"credit_limit_action_name" json:"credit_limit_action_name"`
	SalesInvLimitAction     *int       `db:"sales_inv_limit_action" json:"sales_inv_limit_action"`
	SalesInvLimitActionName *string    `db:"sales_inv_limit_action_name" json:"sales_inv_limit_action_name"`
	ObsLimitAction          *int       `db:"obs_limit_action" json:"obs_limit_action"`
	ObsLimitActionName      *string    `db:"obs_limit_action_name" json:"obs_limit_action_name"`
	OutletEstablishmentDate *string    `db:"outlet_establishment_date" json:"outlet_establishment_date"`
	FileURL                 *string    `db:"file_url" json:"file_url"`
	OutletPrincipalCode     *string    `db:"outlet_principal_code" json:"outlet_principal_code"`
	IsPKPOutlet             *bool      `db:"is_pkp_outlet" json:"is_pkp_outlet"`
	PreDormantStatus        *int       `db:"pre_dormant_status" json:"pre_dormant_status"`
	PrevTransDate           *string    `db:"prev_trans_date" json:"prev_trans_date"`
}

type MOutletContactReads struct {
	CustID                  string  `db:"cust_id" json:"cust_id"`
	OutletID                int64   `db:"outlet_id" json:"outlet_id"`
	ContactName             *string `db:"contact_name" json:"contact_name"`
	JobTitle                *string `db:"job_title" json:"job_title"`
	PhoneNo                 *string `db:"phone_no" json:"phone_no"`
	WaNo                    *string `db:"wa_no" json:"wa_no"`
	Email                   *string `db:"email" json:"email"`
	IdentityNo              *string `db:"identity_no" json:"identity_no"`
	IsWaNo                  *bool   `json:"is_wa_no" db:"is_wa_no"`
	OutletContactId         *int64  `db:"outlet_contact_id" json:"outlet_contact_id"`
	IdentityType            *string `db:"identity_type" json:"identity_type"`
	FaxNumber               *string `db:"fax_number" json:"fax_number"`
	OutletEstablishmentDate *string `db:"outlet_establishment_date" json:"outlet_establishment_date"`
}

type MOutletFromListSimilar struct {
	Count      int    `json:"count" db:"count"`
	OutletName string `json:"outlet_name,omitempty" db:"outlet_name"`
}

type MobileOutletList struct {
	OutletId     int     `db:"outlet_id" json:"outlet_id"`
	OutletCode   string  `db:"outlet_code" json:"outlet_code"`
	OutletName   string  `db:"outlet_name" json:"outlet_name"`
	OutletStatus int     `db:"outlet_status" json:"outlet_status"`
	Address1     string  `db:"address1" json:"address1"`
	Latitude     string  `db:"latitude" json:"latitude"`
	Longitude    string  `db:"longitude" json:"longitude"`
	AvgSalesWeek float64 `db:"avg_sales_week" json:"avg_sales_week"`
}

type MobileOutletDetail struct {
	OutletId    int64  `db:"outlet_id" json:"outlet_id"`
	OutletCode  string `db:"outlet_code" json:"outlet_code"`
	OutletName  string `db:"outlet_name" json:"outlet_name"`
	Address1    string `db:"address1" json:"address1"`
	PhoneNo     string `db:"phone_no" json:"phone_no"`
	BuildingOwn int    `db:"building_own" json:"building_own"`
	FileUrl     string `db:"file_url" json:"file_url"`
	Longitude   string `db:"longitude" json:"longitude"`
	Latitude    string `db:"latitude" json:"latitude"`
}

type MobileOutletContactDetail struct {
	ContactName string `db:"contact_name" json:"contact_name"`
	JobTitle    string `db:"job_title" json:"job_title"`
	PhoneNo     string `db:"phone_no" json:"phone_no"`
	WaNo        string `db:"wa_no" json:"wa_no"`
	Email       string `db:"email" json:"email"`
}

type MOutletCreadFromListOutletVisitList struct {
	Id               int        `json:"id" db:"id"`
	Year             *int       `json:"year" db:"year"`
	Week             *int       `json:"week" db:"week"`
	Date             *time.Time `json:"date" db:"date"`
	Day              string     `json:"day" db:"day"`
	RouteCode        *int       `json:"route_code" db:"route_code"`
	OutletCode       *string    `json:"outlet_code" db:"outlet_code"`
	PjpId            *int       `json:"pjp_id" db:"pjp_id"`
	PjpCode          *int       `json:"pjp_code" db:"pjp_code"`
	Start            *int       `json:"start" db:"start"`
	Finish           *int       `json:"finish" db:"finish"`
	ArriveAt         *int       `json:"arrive_at" db:"arrive_at"`
	SkipAt           *int       `json:"skip_at" db:"skip_at"`
	LeaveAt          *int       `json:"leave_at" db:"leave_at"`
	CreatedAt        *time.Time `json:"created_at" db:"created_at"`
	UpdatedAt        *time.Time `json:"updated_at" db:"updated_at"`
	OutletId         int        `json:"outlet_id" db:"outlet_id"`
	OnHold           *int       `json:"on_hold" db:"on_hold"`
	SkipReason       *string    `json:"skip_reason" db:"skip_reason"`
	ResumeAt         *int       `json:"resume_at" db:"resume_at"`
	IsPlanned        *bool      `json:"is_planned" db:"is_planned"`
	PhotoPath        *string    `json:"photo_path" db:"photo_path"`
	Latitude         *string    `json:"latitude" db:"latitude"`
	Longitude        *string    `json:"longitude" db:"longitude"`
	IsUpdateLocation *bool      `json:"is_update_location" db:"is_update_location"`
	Folder           *string    `json:"folder" db:"folder"`
	FileBase64       *string    `json:"file_base64" db:"file_base64"`
	FileName         *string    `json:"file_name" db:"file_name"`
	FileType         *string    `json:"file_type" db:"file_type"`
	MediaCategory    *string    `json:"media_category" db:"media_category"`
	FileUrl          *string    `json:"file_url" db:"file_url"`
	FileSize         *int64     `json:"file_size" db:"file_size"`
	IsExtraCall      *bool      `json:"is_extra_call" db:"is_extra_call"`
	DestinationType  *string    `json:"destination_type" db:"destination_type"`
}
