package main

import (
	"log"
	"scyllax-tms/config"
	"scyllax-tms/controller"
	"scyllax-tms/exception"
	"scyllax-tms/repository"
	"scyllax-tms/router"
	"scyllax-tms/service"
	"scyllax-tms/utils"

	"github.com/gofiber/fiber/v2/middleware/cors"

	"scyllax-tms/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/fiber/v2/middleware/requestid"
	fiberSwagger "github.com/swaggo/fiber-swagger"
)

//	@title			ScyllaX-TMS API
//	@version		1.0
//	@description	ScyllaX-TMS API in Go using Fiber framework

//	@securityDefinitions.apikey	Bearer
//	@in							header
//	@name						Authorization
//	@description				Type "Bearer" followed by a space and JWT token.

func main() {
	loadConfig, err := config.LoadConfig(".")
	if err != nil {
		panic(exception.NewInternalServerError(err.Error()))
	}

	//Database
	db := config.ConnectionDB(&loadConfig)
	validate := utils.InitializeValidator()

	// environment swagger
	if loadConfig.Environment != "dev" {
		docs.SwaggerInfo.Host = loadConfig.SwaggerHost
		docs.SwaggerInfo.BasePath = loadConfig.SwaggerUrl
	} else {
		docs.SwaggerInfo.Host = "localhost:3000"
		docs.SwaggerInfo.BasePath = "/api/v1"
	}
	// init repository
	shipmentRepo := repository.NewShipmentRepoImpl(db)
	shipmentInvoicesRepo := repository.NewShipmentInvoicesRepoImpl(db)
	vehicleRepo := repository.NewVehicleRepoImpl(db)
	shipmentOrderStatusRepo := repository.NewShipmentOrderStatusRepoImpl(db)
	picklistRepo := repository.NewPicklistRepositoryImpl(db)

	// init service
	shipmentService := service.NewShipmentServiceImpl(shipmentRepo, shipmentInvoicesRepo, validate)
	dmsService := service.NewDmsServiceImpl(shipmentInvoicesRepo)
	visitService := service.NewVisitServiceImpl(shipmentRepo, shipmentInvoicesRepo, shipmentService, validate)
	arriveService := service.NewArriveServiceImpl(shipmentInvoicesRepo, validate)
	productService := service.NewProductServiceImpl(shipmentInvoicesRepo, validate)
	unloadService := service.NewUnloadServiceImpl(shipmentInvoicesRepo, shipmentService, shipmentOrderStatusRepo, validate)
	vehicleService := service.NewVehicleServiceImpl(vehicleRepo, validate)
	rejectService := service.NewRejectServiceImpl(shipmentInvoicesRepo, shipmentService, shipmentOrderStatusRepo, validate)
	outletService := service.NewOutletServiceImpl(shipmentInvoicesRepo, validate)
	reportService := service.NewReportServiceImpl(shipmentInvoicesRepo, validate)
	pickUpService := service.NewPickUpServiceImpl(shipmentInvoicesRepo, shipmentService, validate)
	picklistService := service.NewPicklistServiceImpl(picklistRepo, validate)

	// init controller
	shipmentController := controller.NewShipmentController(shipmentService)
	dmsController := controller.NewDmsController(dmsService, vehicleService)
	visitController := controller.NewVisitController(visitService)
	arriveController := controller.NewArriveController(arriveService)
	unloadController := controller.NewUnloadController(unloadService)
	rejectController := controller.NewRejectController(rejectService)
	outletController := controller.NewOutletController(outletService)
	productController := controller.NewProductController(productService)
	reportController := controller.NewReportController(reportService)
	pickUpController := controller.NewPickUpController(pickUpService)
	picklistController := controller.NewPicklistController(picklistService)

	routes := router.NewRouter(
		shipmentController,
		dmsController,
		visitController,
		arriveController,
		unloadController,
		rejectController,
		outletController,
		productController,
		reportController,
		pickUpController,
		picklistController,
	)

	app := fiber.New(fiber.Config{
		ErrorHandler: exception.ErrorHandler,
	})
	app.Use(recover.New())
	app.Use(requestid.New())
	app.Use(logger.New(logger.Config{
		Format: "[${locals:requestid}] ${ip} - ${method} ${status} ${path} - ${latency}\n",
	}))
	app.Use(cors.New())
	app.Mount("/api/v1", routes)
	app.Get("/*", fiberSwagger.WrapHandler)
	app.Use(func(ctx *fiber.Ctx) error {
		return ctx.Status(404).JSON(fiber.Map{
			"code":     404,
			"status":   "NOT FOUND",
			"errors":   "Page Not Found",
			"trace_id": ctx.Locals("requestid").(string),
		})
	})
	log.Fatal(app.Listen(":" + loadConfig.ServerPort))
}
