-- Migration: mst.distributor_replenishment_setup & mst.distributor_replenishment_approval
-- Date: 2026-04-04
--
-- distributor_replenishment_setup: products / parameters for auto push allocation
--   (warehouse limits, credit, lead time, approval required, etc.).
-- distributor_replenishment_approval: approver users and ordering (level, sequence).
--
-- Enum-like columns use VARCHAR + CHECK (distributor_type, wh_limit_action).
-- credit_limit_action: INT 1 = Restricted, 2 = Unrestricted (matches JSON int in API).
--
-- m_supplier: use FK on sup_id only unless you add UNIQUE (cust_id, sup_id) on m_supplier.
-- If sup_id is not unique/PK on m_supplier, drop fk_distributor_replenishment_setup_supplier
-- and enforce refs in application.

-- ---------------------------------------------------------------------------
-- Parent: mst.distributor_replenishment_setup
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mst.distributor_replenishment_setup (
    cust_id varchar(10) NOT NULL,
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sup_id int4 NOT NULL,
    distributor_id int4 NOT NULL,
    distributor_type varchar(20) NOT NULL,
    wh_limit_action varchar(20) NOT NULL,
    wh_capacity int4 NOT NULL,
    wh_volume int4 NOT NULL,
    credit_limit_action int4 NOT NULL,
    plafon_credit int4 NOT NULL,
    lead_time_days int4 NOT NULL,
    is_approval_required bool NOT NULL DEFAULT false,
    is_active bool NOT NULL DEFAULT true,
    created_by int4 NOT NULL,
    created_at timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by int8 NULL,
    updated_at timestamptz(6) NULL,
    deleted_by int4 NULL,
    deleted_at timestamptz(6) NULL,
    is_del bool NULL DEFAULT false,
    CONSTRAINT distributor_replenishment_setup_pkey PRIMARY KEY (id),
    CONSTRAINT distributor_replenishment_setup_distributor_type_check
        CHECK (distributor_type IN ('FMCG', 'Fresh')),
    CONSTRAINT distributor_replenishment_setup_wh_limit_check
        CHECK (wh_limit_action IN ('Restricted', 'Unrestricted')),
    CONSTRAINT distributor_replenishment_setup_credit_limit_check
        CHECK (credit_limit_action IN (1, 2)),
    CONSTRAINT fk_distributor_replenishment_setup_cust
        FOREIGN KEY (cust_id) REFERENCES smc.m_customer (cust_id),
    CONSTRAINT fk_distributor_replenishment_setup_supplier
        FOREIGN KEY (sup_id) REFERENCES mst.m_supplier (sup_id),
    CONSTRAINT fk_distributor_replenishment_setup_distributor
        FOREIGN KEY (distributor_id) REFERENCES mst.m_distributor (distributor_id)
);

CREATE INDEX IF NOT EXISTS idx_distributor_replenishment_setup_cust_id
    ON mst.distributor_replenishment_setup (cust_id);
CREATE INDEX IF NOT EXISTS idx_distributor_replenishment_setup_sup_id
    ON mst.distributor_replenishment_setup (sup_id);
CREATE INDEX IF NOT EXISTS idx_distributor_replenishment_setup_distributor_id
    ON mst.distributor_replenishment_setup (distributor_id);
CREATE INDEX IF NOT EXISTS idx_distributor_replenishment_setup_is_del
    ON mst.distributor_replenishment_setup (is_del);

COMMENT ON TABLE mst.distributor_replenishment_setup IS 'Distributor replenishment / auto push allocation parameters per supplier & distributor.';
COMMENT ON COLUMN mst.distributor_replenishment_setup.cust_id IS 'Customer id; ref smc.m_customer';
COMMENT ON COLUMN mst.distributor_replenishment_setup.sup_id IS 'Supplier id; ref mst.m_supplier.sup_id (align cust_id in app if needed)';
COMMENT ON COLUMN mst.distributor_replenishment_setup.distributor_id IS 'Distributor id; ref mst.m_distributor (cust_id, distributor_id)';
COMMENT ON COLUMN mst.distributor_replenishment_setup.credit_limit_action IS '1 = Restricted, 2 = Unrestricted';

-- ---------------------------------------------------------------------------
-- Child: mst.distributor_replenishment_approval
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mst.distributor_replenishment_approval (
    cust_id varchar(10) NOT NULL,
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    dist_replenishment_setup_id int4 NOT NULL,
    level int2 NOT NULL,
    "sequence" int2 NOT NULL,
    business_unit int4 NOT NULL,
    pic int4 NOT NULL,
    is_active bool NOT NULL DEFAULT true,
    created_by int4 NOT NULL,
    created_at timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by int8 NULL,
    updated_at timestamptz(6) NULL,
    deleted_by int4 NULL,
    deleted_at timestamptz(6) NULL,
    is_del bool NULL DEFAULT false,
    CONSTRAINT distributor_replenishment_approval_pkey PRIMARY KEY (id),
    CONSTRAINT fk_distributor_replenishment_approval_cust
        FOREIGN KEY (cust_id) REFERENCES smc.m_customer (cust_id),
    CONSTRAINT fk_distributor_replenishment_approval_setup
        FOREIGN KEY (dist_replenishment_setup_id)
            REFERENCES mst.distributor_replenishment_setup (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_distributor_replenishment_approval_emp_pic
        FOREIGN KEY (pic) REFERENCES mst.m_employee (emp_id)
);

CREATE INDEX IF NOT EXISTS idx_distributor_replenishment_approval_cust_id
    ON mst.distributor_replenishment_approval (cust_id);
CREATE INDEX IF NOT EXISTS idx_distributor_replenishment_approval_setup_id
    ON mst.distributor_replenishment_approval (dist_replenishment_setup_id);
CREATE INDEX IF NOT EXISTS idx_distributor_replenishment_approval_is_del
    ON mst.distributor_replenishment_approval (is_del);

COMMENT ON TABLE mst.distributor_replenishment_approval IS 'Approval chain for distributor replenishment setup (level, sequence, PIC).';
COMMENT ON COLUMN mst.distributor_replenishment_approval.dist_replenishment_setup_id IS 'FK to mst.distributor_replenishment_setup.id';
COMMENT ON COLUMN mst.distributor_replenishment_approval.business_unit IS 'Business unit id (see data dictionary; spec ref may vary).';
COMMENT ON COLUMN mst.distributor_replenishment_approval.pic IS 'Person in charge (approver); ref mst.m_employee.emp_id';

-- Rollback (run manually if needed):
-- DROP TABLE IF EXISTS mst.distributor_replenishment_approval;
-- DROP TABLE IF EXISTS mst.distributor_replenishment_setup;
