package entity

type ResponseReturn struct {
	ReturnNo        string  `json:"return_no"`
	ReturnDate      string  `json:"return_date"`
	InvoiceNo       string  `json:"invoice_no"`
	InvoiceDate     string  `json:"invoice_date"`
	SalesmanID      int     `json:"salesman_id"`
	SalesmanCode    string  `json:"salesman_code"`
	SalesmanName    string  `json:"salesman_name"`
	OutletID        int     `json:"outlet_id"`
	OutletCode      string  `json:"outlet_code"`
	OutletName      string  `json:"outlet_name"`
	OutletAddress   string  `json:"outlet_address"`
	OutletLatitude  string  `json:"outlet_latitude"`
	OutletLongitude string  `json:"outlet_longitude"`
	DataStatus      int     `json:"data_status"`
	DataStatusName  string  `json:"data_status_name"`
	TotalVolume     float64 `json:"total_volume"`
	TotalWeight     float64 `json:"total_weight"`
	Details         []struct {
		ReturnDetailID   int     `json:"return_detail_id"`
		OrderDetailID    int     `json:"order_detail_id"`
		ReturnNo         string  `json:"return_no"`
		ProductID        int     `json:"product_id"`
		ProductCode      string  `json:"product_code"`
		ProductName      string  `json:"product_name"`
		WhID             int     `json:"wh_id"`
		WhCode           string  `json:"wh_code"`
		WhName           string  `json:"wh_name"`
		ItemCnd          int     `json:"item_cnd"`
		ItemCndName      string  `json:"item_cnd_name"`
		Qty1             int     `json:"qty1"`
		Qty2             int     `json:"qty2"`
		Qty3             int     `json:"qty3"`
		InvoiceQty1      int     `json:"invoice_qty1"`
		InvoiceQty2      int     `json:"invoice_qty2"`
		InvoiceQty3      int     `json:"invoice_qty3"`
		RemainingQty1    int     `json:"remaining_qty1"`
		RemainingQty2    int     `json:"remaining_qty2"`
		RemainingQty3    int     `json:"remaining_qty3"`
		SellPrice1       int     `json:"sell_price1"`
		SellPrice2       int     `json:"sell_price2"`
		SellPrice3       int     `json:"sell_price3"`
		UnitID1          string  `json:"unit_id1"`
		UnitID2          string  `json:"unit_id2"`
		UnitID3          string  `json:"unit_id3"`
		UnitName1        string  `json:"unit_name1"`
		UnitName2        string  `json:"unit_name2"`
		UnitName3        string  `json:"unit_name3"`
		ConvUnit2        int     `json:"conv_unit2"`
		ConvUnit3        int     `json:"conv_unit3"`
		Vat              int     `json:"vat"`
		VatValue         float64 `json:"vat_value"`
		SubTotal         int     `json:"sub_total"`
		Total            float64 `json:"total"`
		ReturnReasonID   int     `json:"return_reason_id"`
		ReturnReasonCode string  `json:"return_reason_code"`
		ReturnReasonName string  `json:"return_reason_name"`
		Volume           float64 `json:"volume"`
		Weight           float64 `json:"weight"`
	} `json:"details"`
}
