package main

import (
	"log"
	"master/adapter"
	"master/controller"
	"master/pkg/config"
	"master/pkg/config/env"
	"master/pkg/middleware"
	"master/pkg/server"
	"master/pkg/validation"
	"master/repository"
	"master/service"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/monitor"
)

func main() {
	// load config env
	envCfg := env.NewCfgEnv()
	validatorPkg := validation.NewValidator()

	postgreDB, err := config.ConnToDb(envCfg)
	if err != nil {
		log.Println("err:", err.Error())
		panic(err)
	}

	// var redisCfg config.RedisConfig
	// _, errRedisCon := redisCfg.SetConfig().RedisInstance()
	// if errRedisCon != nil {
	// 	panic(errRedisCon)
	// }

	// go func() {
	// Receives all messages starting with "product_price."
	// rabbitmq.SubscribeProductPriceUpdate("ProductPriceUpdate", 5)
	// rabbitmq.Subscribe("events", "C22001.products.events.update", "C22001.products.events.#") // Receives products.events  messages
	// rabbitmq.ConsumerEmail()
	// }()

	// Setup Repository
	txManagerRepository := repository.NewTransactionManager(postgreDB)
	consProductRepository := repository.NewConsProductRepository(postgreDB)
	principalRepository := repository.NewPrincipalRepository(postgreDB)
	productCatRepository := repository.NewProductCatRepository(postgreDB)
	flavorRepository := repository.NewFlavorRepository(postgreDB)
	packSizeRepository := repository.NewPackSizeRepository(postgreDB)
	packTypeRepository := repository.NewPackTypeRepository(postgreDB)
	unitRepository := repository.NewUnitRepository(postgreDB)
	productLineRepository := repository.NewProductLineRepository(postgreDB)
	brandRepository := repository.NewBrandRepository(postgreDB)
	invDiscRepository := repository.NewInvoiceDiscRepository(postgreDB)
	invDiscDetRepository := repository.NewInvoiceDiscDetRepository(postgreDB)
	outletRepository := repository.NewOutletRepository(postgreDB)
	outletLocRepository := repository.NewOutletLocRepository(postgreDB)
	outletTypeRepository := repository.NewOutletTypeRepository(postgreDB)
	outletGroupRepository := repository.NewOutletGroupRepository(postgreDB)
	outletClassRepository := repository.NewOutletClassRepository(postgreDB)
	outletConfigRepository := repository.NewOutletConfigRepository(postgreDB)
	outletConfigStatusRepository := repository.NewOutletConfigStatusRepository(postgreDB)
	outletCodeRepository := repository.NewOutletCodeRepository(postgreDB)
	districtRepository := repository.NewDistrictRepository(postgreDB)
	marketRepository := repository.NewMarketRepository(postgreDB)
	industryRepository := repository.NewIndustryRepository(postgreDB)
	incentiveGroupRepository := repository.NewIncentiveGroupRepository(postgreDB)
	salesTeamRepository := repository.NewSalesTeamRepository(postgreDB)
	salesTypeRepository := repository.NewSalesTypeRepository(postgreDB)
	beatRepository := repository.NewBeatRepository(postgreDB)
	subBeatRepository := repository.NewSubBeatRepository(postgreDB)
	subBrand1Repository := repository.NewSubBrand1Repository(postgreDB)
	subBrand2Repository := repository.NewSubBrand2Repository(postgreDB)
	discGroupRepository := repository.NewDiscGroupRepository(postgreDB)
	priceGroupRepository := repository.NewPriceGroupRepository(postgreDB)
	pluGroupRepository := repository.NewPluGroupRepository(postgreDB)
	convGroupRepository := repository.NewConvGroupRepository(postgreDB)
	returnReasonRepository := repository.NewReturnReasonRepository(postgreDB)
	returnReasonDistributorRepository := repository.NewReturnReasonDistributorRepository(postgreDB)
	pickupReasonRepository := repository.NewPickupReasonRepository(postgreDB)
	cndnRepository := repository.NewCndnRepository(postgreDB)
	empGroupRepository := repository.NewEmpGroupRepository(postgreDB)
	employeeRepository := repository.NewEmployeeRepository(postgreDB)
	warehouseRepository := repository.NewWarehouseRepository(postgreDB)
	bankRepository := repository.NewBankRepository(postgreDB)
	supplierRepository := repository.NewSupplierRepository(postgreDB)
	officialRepository := repository.NewOfficialRepository(postgreDB)
	officialHierarchyRepository := repository.NewOfficialHierarchyRepository(postgreDB)
	productRepository := repository.NewProductRepository(postgreDB)
	productDistRepository := repository.NewProductDistRepository(postgreDB)
	productAssignmentRepository := repository.NewProductAssignmentRepository(postgreDB)
	productMappingRepository := repository.NewProductMappingRepository(postgreDB)
	vehicleRepository := repository.NewVehicleRepository(postgreDB)
	salesmanRepository := repository.NewSalesmanRepository(postgreDB)
	topRepository := repository.NewTopRepository(postgreDB)
	discRepository := repository.NewDiscRepository(postgreDB)
	tprRepository := repository.NewTprRepository(postgreDB)
	tprLimitRepository := repository.NewTprLimitRepository(postgreDB)
	discProductRepository := repository.NewDiscProductRepository(postgreDB)
	pluProductRepository := repository.NewPluProductRepository(postgreDB)
	convGroupDetRepository := repository.NewConvGroupDetRepository(postgreDB)
	msppriceRepository := repository.NewSpPriceRepository(postgreDB)
	remarkPromoRepository := repository.NewDiscRemarkPromoRepository(postgreDB)
	mParkingFundRepository := repository.NewMParkingFundRepository(postgreDB)
	mPeriodsRepository := repository.NewMPeriodsRepository(postgreDB)
	mWeekRepository := repository.NewMWeekRepository(postgreDB)
	mWorkingDayRepository := repository.NewMWorkingDayRepository(postgreDB)
	distPriceRepository := repository.NewDistPriceRepository(postgreDB)
	distPriceGroupRepository := repository.NewDistPriceGroupRepository(postgreDB)
	statusRepository := repository.NewStatusRepository(postgreDB)
	provinceRepository := repository.NewProvinceRepository(postgreDB)
	regencyRepository := repository.NewRegencyRepository(postgreDB)
	divisionRepository := repository.NewMDivisionRepository(postgreDB)
	subDistrictRepository := repository.NewSubDistrictRepository(postgreDB)
	wardRepository := repository.NewWardRepository(postgreDB)
	vehicleTypeRepository := repository.NewVehicleTypeRepository(postgreDB)
	mChannelRepository := repository.NewMChannelRepository(postgreDB)
	regionRepository := repository.NewRegionRepository(postgreDB)
	areaRepository := repository.NewAreaRepository(postgreDB)
	takingOrderRepository := repository.NewTakingOrderRepository(postgreDB)
	subDistributorGroupRepository := repository.NewSubDistributorGroupRepository(postgreDB)
	skipReasonRepository := repository.NewSkipReasonRepository(postgreDB)
	rejectReasonRepository := repository.NewRejectReasonRepository(postgreDB)
	distributorRepository := repository.NewDistributorRepository(postgreDB)
	specialPriceGroupRepository := repository.NewSpecialPriceGroupRepository(postgreDB)
	priceRepository := repository.NewMPriceRepository(postgreDB)
	transactionPriceRepository := repository.NewMTransactionPriceRepository(postgreDB)
	missedPaymentReasonRepository := repository.NewMissedPaymentReasonsRepository(postgreDB)
	unitCoreTaxRepository := repository.NewUnitCoreTaxRepository(postgreDB)
	productCoreTaxRepository := repository.NewProductCoreTaxRepository(postgreDB)
	manageMinimumPriceRepository := repository.NewManageMinimumPriceRepository(postgreDB)
	surveyTemplateRepository := repository.NewSurveyTemplateRepository(postgreDB)
	questionTemplateRepository := repository.NewQuestionTemplateRepository(postgreDB)
	qOptionTemplateRepository := repository.NewQOptionTemplateRepository(postgreDB)
	surveyRepository := repository.NewSurveyRepository(postgreDB)
	surveyReportRepository := repository.NewSurveyReportRepository(postgreDB)
	reportListRepository := repository.NewReportListRepository(postgreDB)
	salesTargetDistributorRepository := repository.NewSalesTargetDistributorRepository(postgreDB)
	salesTargetRepository := repository.NewSalesTargetRepository(postgreDB)
	businessUnitRepository := repository.NewBusinessUnitRepository(postgreDB)
	distributorReplenishmentSetupRepository := repository.NewDistributorReplenishmentSetupRepository(postgreDB)
	automaticReplenishmentProductRepository := repository.NewAutomaticReplenishmentProductRepository(postgreDB)
	productRipeningRepository := repository.NewProductRipeningRepository(postgreDB)
	workingDayCalendarRepository := repository.NewWorkingDayCalendarRepository(postgreDB)

	// setup adapter
	obsAdapter, err := adapter.InitObsAdapter(envCfg.Get("OBS_HUAWEI_AK"), envCfg.Get("OBS_HUAWEI_SK"), envCfg.Get("OBS_HUAWEI_ENDPOINT"), envCfg.Get("OBS_HUAWEI_BUCKET"))
	if err != nil {
		panic(err)
	}

	// Setup Service
	consProductService := service.NewConsProductService(consProductRepository, productRepository)
	principalService := service.NewPrincipalService(principalRepository, productRepository)
	productCatService := service.NewProductCatService(productCatRepository, productRepository)
	flavorService := service.NewFlavorService(flavorRepository, productRepository)
	packSizeService := service.NewPackSizeService(packSizeRepository, productRepository)
	packTypeService := service.NewPackTypeService(packTypeRepository, productRepository)
	unitService := service.NewUnitService(unitRepository, productRepository)
	productLineService := service.NewProductLineService(productLineRepository, brandRepository)
	brandService := service.NewBrandService(brandRepository)
	invDiscService := service.NewInvoiceDiscService(invDiscRepository, invDiscDetRepository)
	outletService := service.NewOutletService(outletRepository, outletConfigRepository, outletCodeRepository, distributorRepository)
	outletService.StartStatusUpdateScheduler(envCfg.Get("OUTLET_STATUS_UPDATE_TIME"))
	outletLocService := service.NewOutletLocService(outletLocRepository)
	outletTypeService := service.NewOutletTypeService(outletTypeRepository)
	outletGroupService := service.NewOutletGroupService(outletGroupRepository)
	outletClassService := service.NewOutletClassService(outletClassRepository)
	outletConfigService := service.NewOutletConfigService(outletConfigRepository)
	outletConfigStatusService := service.NewOutletConfigStatusService(outletConfigStatusRepository)
	outletCodeService := service.NewOutletCodeService(outletCodeRepository)
	districtService := service.NewDistrictService(districtRepository)
	marketService := service.NewMarketService(marketRepository)
	industryService := service.NewIndustryService(industryRepository)
	incentiveGroupService := service.NewIncentiveGroupService(incentiveGroupRepository)
	salesTeamService := service.NewSalesTeamService(salesTeamRepository)
	salesTypeService := service.NewSalesTypeService(salesTypeRepository)
	beatService := service.NewBeatService(beatRepository)
	subBeatService := service.NewSubBeatService(subBeatRepository)
	subBrand1Service := service.NewSubBrand1Service(subBrand1Repository)
	subBrand2Service := service.NewSubBrand2Service(subBrand2Repository, productRepository)
	discGroupService := service.NewDiscGroupService(discGroupRepository)
	priceGroupService := service.NewPriceGroupService(priceGroupRepository)
	pluGroupService := service.NewPluGroupService(pluGroupRepository)
	convGroupService := service.NewConvGroupService(convGroupRepository)
	returnReasonService := service.NewReturnReasonService(returnReasonRepository)
	returnReasonDistributorService := service.NewReturnReasonDistributorService(returnReasonDistributorRepository)
	pickupReasonService := service.NewPickupReasonService(pickupReasonRepository)
	cndnService := service.NewCndnService(cndnRepository)
	empGroupService := service.NewEmpGroupService(empGroupRepository)
	employeeService := service.NewEmployeeService(employeeRepository)
	warehouseService := service.NewWarehouseService(warehouseRepository)
	bankService := service.NewBankService(bankRepository)
	supplierService := service.NewSupplierService(supplierRepository)
	officialService := service.NewOfficialService(officialRepository)
	officialHierarchyService := service.NewOfficialHierarchyService(officialHierarchyRepository)
	productService := service.NewProductService(productRepository)
	productDistService := service.NewProductDistService(productDistRepository)
	productAssignmentService := service.NewProductAssignmentService(productAssignmentRepository, productRepository, distributorRepository, txManagerRepository)
	productMappingService := service.NewProductMappingService(productMappingRepository, productRepository, distributorRepository, txManagerRepository)
	vehicleService := service.NewVehicleService(vehicleRepository)
	salesmanService := service.NewSalesmanService(salesmanRepository, envCfg)
	topService := service.NewTopService(topRepository)
	discService := service.NewDiscService(discRepository)
	tprService := service.NewTprService(tprRepository)
	tprLimitService := service.NewTprLimitService(tprLimitRepository)
	discProductService := service.NewDiscProductService(discProductRepository)
	pluProductService := service.NewPluProductService(pluProductRepository)
	convGroupDetService := service.NewConvGroupDetService(convGroupDetRepository)
	msppriceService := service.NewSpPriceService(envCfg, msppriceRepository, specialPriceGroupRepository,
		outletRepository, outletTypeRepository, outletGroupRepository, transactionPriceRepository)
	remarkPromoService := service.NewRemarkPromoService(remarkPromoRepository)
	mParkingFundService := service.NewMParkingFundService(mParkingFundRepository)
	mPeriodsService := service.NewMPeriodsService(mPeriodsRepository)
	mWeekService := service.NewMWeekService(mWeekRepository)
	mWorkingDayService := service.NewMWorkingDayService(mWorkingDayRepository)
	distPriceService := service.NewDistPriceService(envCfg, distPriceRepository, transactionPriceRepository)
	distPriceGroupService := service.NewDistPriceGroupService(distPriceGroupRepository)
	statusService := service.NewStatusService(statusRepository)
	filesService := service.NewFilesService(envCfg, obsAdapter)
	provinceService := service.NewProvinceService(provinceRepository)
	regencyService := service.NewRegencyService(regencyRepository)
	divisionService := service.NewMDivisionService(divisionRepository)
	subDistrictService := service.NewSubDistrictService(subDistrictRepository)
	wardService := service.NewWardService(wardRepository)
	vehicleTypeService := service.NewVehicleTypeService(vehicleTypeRepository)
	mChannelService := service.NewMChannelService(mChannelRepository)
	regionService := service.NewRegionService(regionRepository, employeeRepository)
	areaService := service.NewAreaService(areaRepository, employeeRepository)
	takingOrderService := service.NewTakingOrderService(takingOrderRepository)
	subDistributorGroupService := service.NewSubDistributorGroupService(subDistributorGroupRepository)
	skipReasonService := service.NewSkipReasonService(skipReasonRepository)
	rejectReasonService := service.NewRejectReasonService(rejectReasonRepository)
	distributorService := service.NewDistributorService(distributorRepository)
	specialPriceGroupService := service.NewSpecialPriceGroupService(specialPriceGroupRepository)
	priceService := service.NewMPriceService(priceRepository, distributorRepository, transactionPriceRepository)
	missedPaymentReasonService := service.NewMissedPaymentReasonsService(missedPaymentReasonRepository)
	unitCoreTaxService := service.NewUnitCoreTaxService(unitCoreTaxRepository)
	productCoreTaxService := service.NewProductCoreTaxService(productCoreTaxRepository)
	manageMinimumPriceService := service.NewManageMinimumPriceService(manageMinimumPriceRepository)
	businessUnitService := service.NewBusinessUnitService(businessUnitRepository, employeeRepository)
	automaticReplenishmentProductService := service.NewAutomaticReplenishmentProductService(
		automaticReplenishmentProductRepository,
		productRepository,
		distributorRepository,
	)
	productRipeningService := service.NewProductRipeningService(productRipeningRepository, productRepository)
	workingDayCalendarService := service.NewWorkingDayCalendarService(workingDayCalendarRepository)
	historyRepository := repository.NewHistoryRepository(postgreDB)
	historyService := service.NewHistoryService(historyRepository, outletService, productService, employeeService)
	surveyTemplateService := service.NewSurveyTemplateService(surveyTemplateRepository, questionTemplateRepository, qOptionTemplateRepository)
	surveyService := service.NewSurveyService(txManagerRepository, surveyRepository, salesmanRepository, surveyTemplateRepository, questionTemplateRepository, qOptionTemplateRepository)
	surveyReportService := service.NewSurveyReportService(surveyReportRepository, reportListRepository, obsAdapter)
	salesTargetService := service.NewSalesTargetService(salesTargetRepository)
	salesTargetDistributorService := service.NewSalesTargetDistributorService(salesTargetDistributorRepository, salesTargetRepository)
	distributorReplenishmentSetupService := service.NewDistributorReplenishmentSetupService(distributorReplenishmentSetupRepository)

	// Setup Controller
	consProductController := controller.NewConsProductController(consProductService, validatorPkg)
	principalController := controller.NewPrincipalController(principalService, validatorPkg)
	productCatController := controller.NewProductCatController(productCatService, validatorPkg)
	flavorController := controller.NewFlavorController(flavorService, validatorPkg)
	packSizeController := controller.NewPackSizeController(packSizeService, validatorPkg)
	packTypeController := controller.NewPackTypeController(packTypeService, validatorPkg)
	unitController := controller.NewUnitController(unitService, validatorPkg)
	productLineController := controller.NewProductLineController(productLineService, validatorPkg)
	brandController := controller.NewBrandController(brandService, validatorPkg)
	invoiceDiscController := controller.NewInvoiceDiscController(invDiscService, validatorPkg)
	outletController := controller.NewOutletController(outletService, validatorPkg)
	outletLocController := controller.NewOutletLocController(outletLocService, validatorPkg)
	outletTypeController := controller.NewOutletTypeController(outletTypeService, validatorPkg)
	outletGroupController := controller.NewOutletGroupController(outletGroupService, validatorPkg)
	outletClassController := controller.NewOutletClassController(outletClassService, validatorPkg)
	outletConfigController := controller.NewOutletConfigController(outletConfigService, outletConfigStatusService, validatorPkg)
	outletCodeController := controller.NewOutletCodeController(outletCodeService)
	districtController := controller.NewDistrictController(districtService, validatorPkg)
	marketController := controller.NewMarketController(marketService, validatorPkg)
	industryController := controller.NewIndustryController(industryService, validatorPkg)
	incentiveGroupController := controller.NewIncentiveGroupController(incentiveGroupService, validatorPkg)
	salesTeamController := controller.NewSalesTeamController(salesTeamService, validatorPkg)
	salesTypeController := controller.NewSalesTypeController(salesTypeService, validatorPkg)
	beatController := controller.NewBeatController(beatService, validatorPkg)
	subBeatController := controller.NewSubBeatController(subBeatService, validatorPkg)
	subBrand1Controller := controller.NewSubBrand1Controller(subBrand1Service, validatorPkg)
	subBrand2Controller := controller.NewSubBrand2Controller(subBrand2Service, validatorPkg)
	discGroupController := controller.NewDiscGroupController(discGroupService, validatorPkg)
	priceGroupController := controller.NewPriceGroupController(priceGroupService, validatorPkg)
	pluGroupController := controller.NewPluGroupController(pluGroupService, validatorPkg)
	convGroupController := controller.NewConvGroupController(convGroupService, validatorPkg)
	returnReasonController := controller.NewReturnReasonController(returnReasonService, validatorPkg)
	returnReasonDistributorController := controller.NewReturnReasonDistributorController(returnReasonDistributorService, validatorPkg)
	pickupReasonController := controller.NewPickupReasonController(pickupReasonService, validatorPkg)
	cndnController := controller.NewCndnController(cndnService, validatorPkg)
	empGroupController := controller.NewEmpGroupController(empGroupService, validatorPkg)
	employeeController := controller.NewEmployeeController(employeeService, validatorPkg)
	warehouseController := controller.NewWarehouseController(warehouseService, validatorPkg)
	bankController := controller.NewBankController(bankService, validatorPkg)
	supplierController := controller.NewSupplierController(supplierService, validatorPkg)
	officialController := controller.NewOfficialController(officialService, validatorPkg)
	officialHierarchyController := controller.NewOfficialHierarchyController(officialHierarchyService, validatorPkg)
	productController := controller.NewProductController(productService, validatorPkg)
	productDistController := controller.NewProductDistController(productDistService, validatorPkg)
	productAssignmentController := controller.NewProductAssignmentController(productAssignmentService, validatorPkg)
	productMappingController := controller.NewProductMappingController(productMappingService, validatorPkg)
	vehicleController := controller.NewVehicleController(vehicleService, validatorPkg)
	salesmanController := controller.NewSalesmanController(salesmanService, validatorPkg)
	topController := controller.NewTopController(topService, validatorPkg)
	discController := controller.NewDiscController(discService, validatorPkg)
	tprController := controller.NewTprController(tprService, validatorPkg)
	tprLimitController := controller.NewTprLimitController(tprLimitService, validatorPkg)
	discProductController := controller.NewDiscProductController(discProductService, validatorPkg)
	pluProductController := controller.NewPluProductController(pluProductService, validatorPkg)
	convGroupDetController := controller.NewConvGroupDetController(convGroupDetService, validatorPkg)
	msppriceController := controller.NewSpPriceController(msppriceService, validatorPkg)
	remarkPromoController := controller.NewRemarkPromoController(remarkPromoService, validatorPkg)
	mParkingFundController := controller.NewMParkingFundController(mParkingFundService, validatorPkg)
	mPeriodsController := controller.NewMPeriodsController(mPeriodsService, validatorPkg)
	mWeekController := controller.NewMWeekController(mWeekService, validatorPkg)
	mWorkingDayController := controller.NewMWorkingDayController(mWorkingDayService, validatorPkg)
	distPriceController := controller.NewDistPriceController(distPriceService, validatorPkg)
	distPriceGroupController := controller.NewDistPriceGroupController(distPriceGroupService, validatorPkg)
	statusController := controller.NewStatusController(statusService, validatorPkg)
	filesController := controller.NewFilesController(filesService, validatorPkg)
	provinceController := controller.NewProvinceController(provinceService, validatorPkg)
	regencyController := controller.NewRegencyController(regencyService, validatorPkg)
	divisionController := controller.NewMDivisionController(divisionService, validatorPkg)
	subDistrictController := controller.NewSubDistrictController(subDistrictService, validatorPkg)
	wardController := controller.NewWardController(wardService, validatorPkg)
	vehicleTypeController := controller.NewVehicleTypeController(vehicleTypeService, validatorPkg)
	mChannelController := controller.NewMChannelController(mChannelService, validatorPkg)
	regionController := controller.NewRegionController(regionService, validatorPkg)
	areaController := controller.NewAreaController(areaService, validatorPkg)
	takingOrderController := controller.NewTakingOrderController(takingOrderService, validatorPkg)
	subDistributorGroupController := controller.NewSubDistributorGroupController(subDistributorGroupService, validatorPkg)
	skipReasonController := controller.NewSkipReasonController(skipReasonService, validatorPkg)
	rejectReasonController := controller.NewRejectReasonController(rejectReasonService, validatorPkg)
	distributorController := controller.NewDistributorController(distributorService, validatorPkg)
	specialPriceGroupController := controller.NewSpecialPriceGroupController(specialPriceGroupService, validatorPkg)
	priceController := controller.NewMPriceController(priceService, validatorPkg)
	missedPaymentReasonController := controller.NewMissedPaymentReasonsController(missedPaymentReasonService, validatorPkg)
	unitCoreTaxController := controller.NewUnitCoreTaxController(unitCoreTaxService, validatorPkg)
	productCoreTaxController := controller.NewProductCoreTaxController(productCoreTaxService, validatorPkg)
	manageMinimumPriceController := controller.NewManageMinimumPriceController(manageMinimumPriceService, validatorPkg)
	businessUnitController := controller.NewBusinessUnitController(businessUnitService, validatorPkg)
	automaticReplenishmentProductController := controller.NewAutomaticReplenishmentProductController(automaticReplenishmentProductService, validatorPkg)
	productRipeningController := controller.NewProductRipeningController(productRipeningService, validatorPkg)
	workingDayCalendarController := controller.NewWorkingDayCalendarController(workingDayCalendarService, validatorPkg)
	historyController := controller.NewHistoryController(historyService, validatorPkg)
	surveyTemplateController := controller.NewSurveyTemplateController(surveyTemplateService, validatorPkg)
	surveyController := controller.NewSurveyController(surveyService, validatorPkg)
	surveyReportController := controller.NewSurveyReportController(surveyReportService, validatorPkg)
	salesTargetDistributorController := controller.NewSalesTargetDistributorController(salesTargetDistributorService, salesTargetService, validatorPkg)
	salesTargetController := controller.NewSalesTargetController(salesTargetService, validatorPkg)
	distributorReplenishmentSetupController := controller.NewDistributorReplenishmentSetupController(distributorReplenishmentSetupService, validatorPkg)

	// define Fiber Framework config
	fiberCfg := config.NewFiberConfig(envCfg)
	app := fiber.New(fiberCfg)

	// middleware
	middleware.AppMiddleware(app, envCfg) // Register Fiber's middleware for app.

	// This route path for test service is running "/"
	app.Get("/ping", func(c *fiber.Ctx) error {
		return c.SendString("It works")
	})
	app.Get("/metrics", monitor.New(monitor.Config{Title: "Master Service Metrics Page"}))

	// route.PublicRoutes(app)
	consProductController.Route(app)
	principalController.Route(app)
	productCatController.Route(app)
	flavorController.Route(app)
	packSizeController.Route(app)
	packTypeController.Route(app)
	unitController.Route(app)
	productLineController.Route(app)
	brandController.Route(app)
	invoiceDiscController.Route(app)
	outletController.Route(app)
	outletCodeController.Route(app)
	outletLocController.Route(app)
	outletTypeController.Route(app)
	outletGroupController.Route(app)
	outletClassController.Route(app)
	outletConfigController.Route(app)
	districtController.Route(app)
	marketController.Route(app)
	industryController.Route(app)
	incentiveGroupController.Route(app)
	salesTeamController.Route(app)
	salesTypeController.Route(app)
	beatController.Route(app)
	subBeatController.Route(app)
	subBrand1Controller.Route(app)
	subBrand2Controller.Route(app)
	discGroupController.Route(app)
	priceGroupController.Route(app)
	pluGroupController.Route(app)
	convGroupController.Route(app)
	returnReasonController.Route(app)
	returnReasonDistributorController.Route(app)
	pickupReasonController.Route(app)
	cndnController.Route(app)
	empGroupController.Route(app)
	employeeController.Route(app)
	warehouseController.Route(app)
	bankController.Route(app)
	supplierController.Route(app)
	officialController.Route(app)
	officialHierarchyController.Route(app)
	productController.Route(app)
	productDistController.Route(app)
	productAssignmentController.Route(app)
	productMappingController.Route(app)
	vehicleController.Route(app)
	salesmanController.Route(app)
	topController.Route(app)
	discController.Route(app)
	tprController.Route(app)
	tprLimitController.Route(app)
	discProductController.Route(app)
	pluProductController.Route(app)
	convGroupDetController.Route(app)
	msppriceController.Route(app)
	remarkPromoController.Route(app)
	mParkingFundController.Route(app)
	mPeriodsController.Route(app)
	mWeekController.Route(app)
	mWorkingDayController.Route(app)
	distPriceController.Route(app)
	distPriceGroupController.Route(app)
	statusController.Route(app)
	filesController.Route(app)
	provinceController.Route(app)
	regencyController.Route(app)
	divisionController.Route(app)
	subDistrictController.Route(app)
	wardController.Route(app)
	vehicleTypeController.Route(app)
	mChannelController.Route(app)
	regionController.Route(app)
	areaController.Route(app)
	takingOrderController.Route(app)
	subDistributorGroupController.Route(app)
	skipReasonController.Route(app)
	rejectReasonController.Route(app)
	distributorController.Route(app)
	specialPriceGroupController.Route(app)
	priceController.Route(app)
	missedPaymentReasonController.Route(app)
	unitCoreTaxController.Route(app)
	productCoreTaxController.Route(app)
	manageMinimumPriceController.Route(app)
	businessUnitController.Route(app)
	automaticReplenishmentProductController.Route(app)
	productRipeningController.Route(app)
	workingDayCalendarController.Route(app)
	historyController.Route(app)
	surveyTemplateController.Route(app)
	surveyController.Route(app)
	surveyReportController.Route(app)
	salesTargetDistributorController.Route(app)
	salesTargetController.Route(app)
	distributorReplenishmentSetupController.Route(app)

	// start fiber server
	server.FiberServerWithGracefulShutdown(app, envCfg)
}
