ALTER TABLE pjp.route_outlet_additional
ADD COLUMN IF NOT EXISTS verified_date TIMESTAMP DEFAULT NULL,
ADD COLUMN IF NOT EXISTS old_pjp_id BIGINT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS old_pjp_code BIGINT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS old_route_code BIGINT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS old_route_name VARCHAR(125) DEFAULT NULL;
