CREATE TABLE IF NOT EXISTS pjp.routes (
    id SERIAL PRIMARY KEY,
    route_code BIGINT UNIQUE NOT NULL,
    route_name VARCHAR(125) NOT NULL,
    is_assign BOOLEAN DEFAULT FALSE,
    cust_id VARCHAR(125) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
