ALTER TABLE pjp.routes 
    ADD COLUMN pjp_id INT;

-- Tambahkan kembali serial dan primary key pada kolom id
CREATE TABLE pjp.route_outlet_history AS
SELECT * FROM pjp.route_outlet
LIMIT 0; -- hanya struktur, tanpa data

-- 2. Tambahkan kolom week dan year
ALTER TABLE pjp.route_outlet_history
ADD COLUMN index_day INT,
ADD COLUMN start_week TIMESTAMP,
ADD COLUMN is_in_current_year BOOLEAN,
ADD COLUMN date DATE,
ADD COLUMN week INT,
ADD COLUMN year INT;



-- Tambahkan kembali serial dan primary key pada kolom id
ALTER TABLE pjp.route_outlet_history 
    ALTER COLUMN id SET NOT NULL,
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY, -- atau gunakan SERIAL
    ADD PRIMARY KEY (id);

ALTER TABLE pjp.outlet_visit_list
    DROP CONSTRAINT fk_route_pop_daily_route;

-- menambah foreign key
-- ALTER TABLE pjp.route_outlet_history
-- ADD CONSTRAINT fk_route_code
-- FOREIGN KEY (route_code)
-- REFERENCES pjp.routes(route_code)
-- ON DELETE CASCADE
-- ON UPDATE CASCADE;

ALTER TABLE pjp.route_pop_daily
ADD CONSTRAINT unique_route_entry
UNIQUE (year, week, date, day, route_code, pjp_id, pjp_code, cust_id, status);

-- 1. Drop existing unique constraint
ALTER TABLE pjp.permanent_journey_plans
DROP CONSTRAINT permanent_journey_plans_pjp_code_key;

-- 2. Add new unique constraint on (pjp_code, cust_id)
ALTER TABLE pjp.permanent_journey_plans
ADD CONSTRAINT permanent_journey_plans_pjp_code_cust_id_key UNIQUE (pjp_code, cust_id);

ALTER TABLE pjp.routes 
ADD COLUMN is_pjp_old BOOLEAN;

ALTER TABLE pjp.route_outlet_history
ADD COLUMN is_additional BOOLEAN DEFAULT false;



-- -- buat triger
-- CREATE OR REPLACE FUNCTION update_route_name_on_change()
-- RETURNS TRIGGER AS $$
-- BEGIN
--   -- Update route_outlet_history
--   UPDATE pjp.route_outlet_history
--   SET route_name = NEW.route_name
--   WHERE route_code = NEW.route_code;

--   -- Update route_outlet
--   UPDATE pjp.route_outlet
--   SET route_name = NEW.route_name
--   WHERE route_code = NEW.route_code;

--   RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;


-- -- eksekusi trigger
-- CREATE TRIGGER trg_update_route_name
-- AFTER UPDATE OF route_name ON pjp.routes
-- FOR EACH ROW
-- EXECUTE FUNCTION update_route_name_on_change();


-- -- 3. Masukkan data dari pjp.route_outlet sebanyak 53x dengan week 1-53 dan year 2025
-- INSERT INTO pjp.route_outlet_history (
--     route_code,
--     route_name,
--     outlet_id,
--     outlet_code,
--     outlet_name,
--     longitude,
--     latitude,
--     outlet_status,
--     outlet_address,
--     pjp_id,
--     pjp_code,
--     cust_id,
--     status,
--     created_at,
--     updated_at,
--     verified_date,
--     old_pjp_id,
--     old_pjp_code,
--     old_route_code,
--     old_route_name,
--     photo,
--     signature,
--     avg_sales_week,
--     week,
--     year
-- )
-- SELECT
--     ro.route_code,
--     ro.route_name,
--     ro.outlet_id,
--     ro.outlet_code,
--     ro.outlet_name,
--     ro.longitude,
--     ro.latitude,
--     ro.outlet_status,
--     ro.outlet_address,
--     ro.pjp_id,
--     ro.pjp_code,
--     ro.cust_id,
--     ro.status,
--     ro.created_at,
--     ro.updated_at,
--     ro.verified_date,
--     ro.old_pjp_id,
--     ro.old_pjp_code,
--     ro.old_route_code,
--     ro.old_route_name,
--     ro.photo,
--     ro.signature,
--     ro.avg_sales_week,
--     gs.week,
--     2025 AS year
-- FROM 
--     pjp.route_outlet ro,
--     generate_series(1, 53) AS gs(week);
