-- Migration: Create arrival_report table
-- Description: Stores arrival validation data for mobile visits
-- Based on: docs/Mobile - Arrive - Validasi Geotaging_BE.md

CREATE TABLE IF NOT EXISTS pjp.arrival_report (
    arrival_id SERIAL PRIMARY KEY,
    cust_id VARCHAR(50) NOT NULL,
    outlet_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    activity VARCHAR(50),
    arrival_longitude VARCHAR(50),
    arrival_latitude VARCHAR(50),
    outlet_longitude VARCHAR(50),
    outlet_latitude VARCHAR(50),
    distance_meter INTEGER,
    allowed_radius INTEGER,
    location_status VARCHAR(50),
    created_by VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_by VARCHAR(100),
    updated_at TIMESTAMP,
    deleted_by VARCHAR(100),
    deleted_at TIMESTAMP,
    is_del BOOLEAN DEFAULT FALSE
);

-- Add comments for documentation
COMMENT ON TABLE pjp.arrival_report IS 'Stores arrival validation data for mobile visits';
COMMENT ON COLUMN pjp.arrival_report.arrival_id IS 'Primary key, auto-generated by BE';
COMMENT ON COLUMN pjp.arrival_report.cust_id IS 'Customer ID from user login';
COMMENT ON COLUMN pjp.arrival_report.outlet_id IS 'Outlet ID from FE request body';
COMMENT ON COLUMN pjp.arrival_report.user_id IS 'User ID from FE request body';
COMMENT ON COLUMN pjp.arrival_report.activity IS 'Activity type from FE request body (arrive/leave)';
COMMENT ON COLUMN pjp.arrival_report.arrival_longitude IS 'Arrival longitude from FE request body (current location)';
COMMENT ON COLUMN pjp.arrival_report.arrival_latitude IS 'Arrival latitude from FE request body (current location)';
COMMENT ON COLUMN pjp.arrival_report.outlet_longitude IS 'Outlet longitude from FE request body';
COMMENT ON COLUMN pjp.arrival_report.outlet_latitude IS 'Outlet latitude from FE request body';
COMMENT ON COLUMN pjp.arrival_report.distance_meter IS 'Distance in meters from FE request body';
COMMENT ON COLUMN pjp.arrival_report.allowed_radius IS 'Allowed radius from FE request body';
COMMENT ON COLUMN pjp.arrival_report.location_status IS 'Location status from FE request body (IN_RADIUS/FORCED_OUT_OF_RADIUS)';
COMMENT ON COLUMN pjp.arrival_report.created_by IS 'User who performed the activity';
COMMENT ON COLUMN pjp.arrival_report.created_at IS 'Timestamp when user performed arrive';

-- Create index for common queries
CREATE INDEX IF NOT EXISTS idx_arrival_report_cust_id ON pjp.arrival_report(cust_id);
CREATE INDEX IF NOT EXISTS idx_arrival_report_outlet_id ON pjp.arrival_report(outlet_id);
CREATE INDEX IF NOT EXISTS idx_arrival_report_user_id ON pjp.arrival_report(user_id);
