CREATE TABLE IF NOT EXISTS mst.product_ripening (
    cust_id VARCHAR(10) NOT NULL,
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    distributor_id BIGINT NOT NULL,
    pro_id BIGINT NOT NULL,
    per_year INT NOT NULL,
    per_id INT NOT NULL,
    week_id INT NOT NULL,
    sunday_qty INT NOT NULL DEFAULT 0,
    monday_qty INT NOT NULL DEFAULT 0,
    tuesday_qty INT NOT NULL DEFAULT 0,
    wednesday_qty INT NOT NULL DEFAULT 0,
    thursday_qty INT NOT NULL DEFAULT 0,
    friday_qty INT NOT NULL DEFAULT 0,
    saturday_qty INT NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at timestamptz NULL,
    deleted_by BIGINT NULL,
    deleted_at timestamptz NULL,
    is_del BOOL NOT NULL DEFAULT false,
    CONSTRAINT product_ripening_pkey PRIMARY KEY (id),
    CONSTRAINT product_ripening_qty_non_negative CHECK (
        sunday_qty >= 0 AND monday_qty >= 0 AND tuesday_qty >= 0 AND
        wednesday_qty >= 0 AND thursday_qty >= 0 AND friday_qty >= 0 AND saturday_qty >= 0
    ),
    CONSTRAINT fk_product_ripening_customer FOREIGN KEY (cust_id) REFERENCES smc.m_customer (cust_id),
    CONSTRAINT fk_product_ripening_distributor FOREIGN KEY (distributor_id) REFERENCES mst.m_distributor (distributor_id),
    CONSTRAINT fk_product_ripening_product FOREIGN KEY (pro_id) REFERENCES mst.m_product (pro_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_ripening_plan
    ON mst.product_ripening (cust_id, distributor_id, pro_id, per_year, per_id, week_id)
    WHERE is_del = false;

CREATE INDEX IF NOT EXISTS idx_product_ripening_distributor_week
    ON mst.product_ripening (cust_id, distributor_id, per_year, per_id, week_id)
    WHERE is_del = false;

CREATE INDEX IF NOT EXISTS idx_product_ripening_product
    ON mst.product_ripening (cust_id, pro_id)
    WHERE is_del = false;

COMMENT ON TABLE mst.product_ripening IS 'Weekly ripening plan per distributor and product with daily Sunday-Saturday quantities.';
COMMENT ON COLUMN mst.product_ripening.cust_id IS 'Principal customer id that owns the ripening plan.';
COMMENT ON COLUMN mst.product_ripening.distributor_id IS 'Distributor id assigned to the PIC in distributor replenishment setup.';
COMMENT ON COLUMN mst.product_ripening.pro_id IS 'Principal product id. Product must also be assigned to the distributor through m_product_dist.';
