ALTER TABLE tms.shipment_invoices
ADD COLUMN IF NOT EXISTS arrive_at BIGINT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS unload_at BIGINT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS leave_at BIGINT DEFAULT NULL;