ALTER TABLE tms.shipment_invoices
ADD COLUMN IF NOT EXISTS warehouse_latitude VARCHAR(125) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS warehouse_longitude VARCHAR(125) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS outlet_latitude VARCHAR(125) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS outlet_longitude VARCHAR(125) DEFAULT NULL;