CREATE TABLE IF NOT EXISTS tms.shipments (
    id SERIAL PRIMARY KEY,
    shipment_no VARCHAR(125) NOT NULL,
    driver_id BIGINT NULL,
    driver_name VARCHAR(125) NULL,
    helper_id BIGINT NULL,
    helper_name VARCHAR(125) NULL,
    vehicle_id BIGINT NOT NULL,
    vehicle_type VARCHAR(125) NOT NULL,
    vehicle_name VARCHAR(125) NOT NULL,
    vehicle_no VARCHAR(125) NULL,
    length REAL,
    width REAL,
    height REAL,
    volume REAL,
    weight REAL,
    delivery_date DATE NOT NULL,
    start BIGINT NULL,
    finish BIGINT NULL,
    status VARCHAR(125) DEFAULT 'Planned',
    cust_id VARCHAR(125) NULL,
    shipment_type VARCHAR(125) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT (now()),
    updated_at timestamptz NULL
);