ALTER TABLE tms.shipment_invoices
ADD COLUMN IF NOT EXISTS product_code VARCHAR(125) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS photo VARCHAR(125) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS signature VARCHAR(125) DEFAULT NULL;
