CREATE TABLE IF NOT EXISTS tms.shipment_invoices (
    id SERIAL PRIMARY KEY,
    shipment_no VARCHAR(125) NULL,
    order_no VARCHAR(125) NULL,
    invoice_no VARCHAR(125) NULL,
    outlet_id BIGINT NULL,
    outlet_name VARCHAR(125) NULL,
    outlet_code VARCHAR(125) NULL,
    outlet_address VARCHAR(125) NULL,
    outlet_status VARCHAR(125) NULL,
    salesman_id BIGINT NULL,
    salesman_name VARCHAR(125),
    product_id BIGINT NULL,
    product_name VARCHAR(125),
    product_status VARCHAR(125),
    delivery_date DATE NOT NULL,
    sku VARCHAR(125),
    route_id BIGINT NULL,
    cust_id VARCHAR(125) NULL,
    status VARCHAR(125) NULL,
    volume REAL,
    weight REAL,
    created_at timestamptz NOT NULL DEFAULT (now()),
    updated_at timestamptz NULL
);