ALTER TABLE tms.shipment_invoices
ADD COLUMN IF NOT EXISTS qty_reject_1 BIGINT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS qty_reject_2 BIGINT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS qty_reject_3 BIGINT DEFAULT NULL;