ALTER TABLE tms.shipment_invoices
ADD COLUMN IF NOT EXISTS qty1 BIGINT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS qty2 BIGINT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS qty3 BIGINT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS conv_unit1 BIGINT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS conv_unit2 BIGINT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS conv_unit3 BIGINT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS unit_id1 VARCHAR(125) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS unit_id2 VARCHAR(125) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS unit_id3 VARCHAR(125) DEFAULT NULL;