ALTER TABLE tms.shipment_invoices
ADD COLUMN IF NOT EXISTS total_bruto NUMERIC(20,4) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS total_volume_disc NUMERIC(20,4) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS total_promo NUMERIC(20,4) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS total_ppn NUMERIC(20,4) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS due_date DATE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS sell_price1 NUMERIC(10,2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS sell_price2 NUMERIC(10,2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS sell_price3 NUMERIC(10,2) DEFAULT NULL;