ALTER TABLE tms.shipment_invoices
ADD COLUMN IF NOT EXISTS invoice_date DATE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS total_belum_bayar NUMERIC(20,4) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS pay_type_name VARCHAR(125) DEFAULT NULL;
