ALTER TABLE picklist.order_product
ADD COLUMN volume1 INT DEFAULT 0,
ADD COLUMN volume2 INT DEFAULT 0,
ADD COLUMN volume3 INT DEFAULT 0,
ADD COLUMN weight1 INT DEFAULT 0,
ADD COLUMN weight2 INT DEFAULT 0,
ADD COLUMN weight3 INT DEFAULT 0;
