package model

import (
	"time"
)

type DistPrice struct {
	CustId           string     `db:"cust_id" json:"cust_id"`
	DistPriceId      int64      `db:"dist_price_id" json:"dist_price_id"`
	DistPriceGroupId int64      `db:"dist_price_group_id" json:"dist_price_group_id"`
	StartDate        *string    `db:"start_date" json:"start_date"`
	EndDate          *string    `db:"end_date" json:"end_date"`
	ProId            int64      `db:"pro_id" json:"pro_id"`
	UnitId1          string     `db:"unit_id1" json:"unit_id1"`
	UnitId2          string     `db:"unit_id2" json:"unit_id2"`
	UnitId3          string     `db:"unit_id3" json:"unit_id3"`
	UnitId4          *string    `db:"unit_id4" json:"unit_id4"`
	UnitId5          *string    `db:"unit_id5" json:"unit_id5"`
	ConvUnit2        float32    `db:"conv_unit2" json:"conv_unit2"`
	ConvUnit3        float32    `db:"conv_unit3" json:"conv_unit3"`
	ConvUnit4        float32    `db:"conv_unit4" json:"conv_unit4"`
	ConvUnit5        float32    `db:"conv_unit5" json:"conv_unit5"`
	PurchPrice1      float64    `db:"purch_price1" json:"purch_price1"`
	PurchPrice2      float64    `db:"purch_price2" json:"purch_price2"`
	PurchPrice3      float64    `db:"purch_price3" json:"purch_price3"`
	PurchPrice4      *float64   `db:"purch_price4" json:"purch_price4"`
	PurchPrice5      *float64   `db:"purch_price5" json:"purch_price5"`
	SellPrice1       float64    `db:"sell_price1" json:"sell_price1"`
	SellPrice2       float64    `db:"sell_price2" json:"sell_price2"`
	SellPrice3       float64    `db:"sell_price3" json:"sell_price3"`
	SellPrice4       *float64   `db:"sell_price4" json:"sell_price4"`
	SellPrice5       *float64   `db:"sell_price5" json:"sell_price5"`
	IsDel            bool       `db:"is_del" json:"is_del"`
	CreatedBy        *int64     `db:"created_by,omitempty" json:"created_by"`
	CreatedAt        *time.Time `db:"created_at,omitempty" json:"created_at"`
	UpdatedBy        *int64     `db:"updated_by,omitempty" json:"updated_by"`
	UpdatedAt        *time.Time `db:"updated_at,omitempty" json:"updated_at"`
	DeletedBy        *int64     `db:"deleted_by,omitempty" json:"deleted_by"`
	DeletedAt        *time.Time `db:"deleted_at,omitempty" json:"deleted_at"`
	DistPriceIdOld   *int64     `db:"dist_price_id_old,omitempty" json:"dist_price_id_old"`
}

type DistPriceDetail struct {
	CustId              string     `db:"cust_id" json:"cust_id"`
	DistPriceId         int64      `db:"dist_price_id" json:"dist_price_id"`
	DistPriceGroupId    int64      `db:"dist_price_group_id" json:"dist_price_group_id"`
	DistPriceGrpCode    string     `db:"dist_price_grp_code" json:"dist_price_grp_code"`
	DistPriceGrpName    string     `db:"dist_price_grp_name" json:"dist_price_grp_name"`
	StartDate           *time.Time `db:"start_date" json:"start_date"`
	EndDate             *time.Time `db:"end_date" json:"end_date"`
	ProId               int64      `db:"pro_id" json:"pro_id"`
	ProCode             string     `db:"pro_code" json:"pro_code"`
	ProName             string     `db:"pro_name" json:"pro_name"`
	UnitId1             string     `db:"unit_id1" json:"unit_id1"`
	UnitId2             string     `db:"unit_id2" json:"unit_id2"`
	UnitId3             string     `db:"unit_id3" json:"unit_id3"`
	UnitId4             *string    `db:"unit_id4" json:"unit_id4"`
	UnitId5             *string    `db:"unit_id5" json:"unit_id5"`
	UnitName1           *string    `db:"unit_name1" json:"unit_name1"`
	UnitName2           *string    `db:"unit_name2" json:"unit_name2"`
	UnitName3           *string    `db:"unit_name3" json:"unit_name3"`
	UnitName4           *string    `db:"unit_name4" json:"unit_name4"`
	UnitName5           *string    `db:"unit_name5" json:"unit_name5"`
	ConvUnit2           float32    `db:"conv_unit2" json:"conv_unit2"`
	ConvUnit3           float32    `db:"conv_unit3" json:"conv_unit3"`
	ConvUnit4           float32    `db:"conv_unit4" json:"conv_unit4"`
	ConvUnit5           float32    `db:"conv_unit5" json:"conv_unit5"`
	PurchPrice1         float64    `db:"purch_price1" json:"purch_price1"`
	PurchPrice2         float64    `db:"purch_price2" json:"purch_price2"`
	PurchPrice3         float64    `db:"purch_price3" json:"purch_price3"`
	PurchPrice4         *float64   `db:"purch_price4" json:"purch_price4"`
	PurchPrice5         *float64   `db:"purch_price5" json:"purch_price5"`
	SellPrice1          float64    `db:"sell_price1" json:"sell_price1"`
	SellPrice2          float64    `db:"sell_price2" json:"sell_price2"`
	SellPrice3          float64    `db:"sell_price3" json:"sell_price3"`
	SellPrice4          *float64   `db:"sell_price4" json:"sell_price4"`
	SellPrice5          *float64   `db:"sell_price5" json:"sell_price5"`
	UpdatedByName       *string    `db:"updated_by_name" json:"updated_by_name"`
	UpdatedAt           *time.Time `db:"updated_at,omitempty" json:"updated_at"`
	DistPriceIdOld      *int64     `db:"dist_price_id_old" json:"dist_price_id_old"`
	DistPriceGroupIdOld *int64     `db:"dist_price_group_id_old" json:"dist_price_group_id_old"`
	DistPriceGrpCodeOld *string    `db:"dist_price_grp_code_old" json:"dist_price_grp_code_old"`
	DistPriceGrpNameOld *string    `db:"dist_price_grp_name_old" json:"dist_price_grp_name_old"`
	StartDateOld        *time.Time `db:"start_date_old" json:"start_date_old"`
	EndDateOld          *time.Time `db:"end_date_old" json:"end_date_old"`
	ProIdOld            *int64     `db:"pro_id_old" json:"pro_id_old"`
	UnitId1Old          *string    `db:"unit_id1_old" json:"unit_id1_old"`
	UnitId2Old          *string    `db:"unit_id2_old" json:"unit_id2_old"`
	UnitId3Old          *string    `db:"unit_id3_old" json:"unit_id3_old"`
	UnitId4Old          *string    `db:"unit_id4_old" json:"unit_id4_old"`
	UnitId5Old          *string    `db:"unit_id5_old" json:"unit_id5_old"`
	UnitName1Old        *string    `db:"unit_name1_old" json:"unit_name1_old"`
	UnitName2Old        *string    `db:"unit_name2_old" json:"unit_name2_old"`
	UnitName3Old        *string    `db:"unit_name3_old" json:"unit_name3_old"`
	UnitName4Old        *string    `db:"unit_name4_old" json:"unit_name4_old"`
	UnitName5Old        *string    `db:"unit_name5_old" json:"unit_name5_old"`
	ConvUnit2Old        *float32   `db:"conv_unit2_old" json:"conv_unit2_old"`
	ConvUnit3Old        *float32   `db:"conv_unit3_old" json:"conv_unit3_old"`
	ConvUnit4Old        *float32   `db:"conv_unit4_old" json:"conv_unit4_old"`
	ConvUnit5Old        *float32   `db:"conv_unit5_old" json:"conv_unit5_old"`
	PurchPrice1Old      *float64   `db:"purch_price1_old" json:"purch_price1_old"`
	PurchPrice2Old      *float64   `db:"purch_price2_old" json:"purch_price2_old"`
	PurchPrice3Old      *float64   `db:"purch_price3_old" json:"purch_price3_old"`
	PurchPrice4Old      *float64   `db:"purch_price4_old" json:"purch_price4_old"`
	PurchPrice5Old      *float64   `db:"purch_price5_old" json:"purch_price5_old"`
	SellPrice1Old       *float64   `db:"sell_price1_old" json:"sell_price1_old"`
	SellPrice2Old       *float64   `db:"sell_price2_old" json:"sell_price2_old"`
	SellPrice3Old       *float64   `db:"sell_price3_old" json:"sell_price3_old"`
	SellPrice4Old       *float64   `db:"sell_price4_old" json:"sell_price4_old"`
	SellPrice5Old       *float64   `db:"sell_price5_old" json:"sell_price5_old"`
	Status              int        `db:"status" json:"status"`
}

type DistPriceList struct {
	CustId           string     `db:"cust_id" json:"cust_id"`
	DistPriceId      int64      `db:"dist_price_id" json:"dist_price_id"`
	DistPriceGroupId int64      `db:"dist_price_group_id" json:"dist_price_group_id"`
	DistPriceGrpCode string     `db:"dist_price_grp_code" json:"dist_price_grp_code"`
	DistPriceGrpName string     `db:"dist_price_grp_name" json:"dist_price_grp_name"`
	StartDate        *time.Time `db:"start_date" json:"start_date"`
	EndDate          *time.Time `db:"end_date" json:"end_date"`
	ProId            int64      `db:"pro_id" json:"pro_id"`
	ProCode          string     `db:"pro_code" json:"pro_code"`
	ProName          string     `db:"pro_name" json:"pro_name"`
	UnitId1          string     `db:"unit_id1" json:"unit_id1"`
	UnitId2          string     `db:"unit_id2" json:"unit_id2"`
	UnitId3          string     `db:"unit_id3" json:"unit_id3"`
	UnitId4          *string    `db:"unit_id4" json:"unit_id4"`
	UnitId5          *string    `db:"unit_id5" json:"unit_id5"`
	ConvUnit2        float32    `db:"conv_unit2" json:"conv_unit2"`
	ConvUnit3        float32    `db:"conv_unit3" json:"conv_unit3"`
	ConvUnit4        float32    `db:"conv_unit4" json:"conv_unit4"`
	ConvUnit5        float32    `db:"conv_unit5" json:"conv_unit5"`
	PurchPrice1      float64    `db:"purch_price1" json:"purch_price1"`
	PurchPrice2      float64    `db:"purch_price2" json:"purch_price2"`
	PurchPrice3      float64    `db:"purch_price3" json:"purch_price3"`
	PurchPrice4      *float64   `db:"purch_price4" json:"purch_price4"`
	PurchPrice5      *float64   `db:"purch_price5" json:"purch_price5"`
	SellPrice1       float64    `db:"sell_price1" json:"sell_price1"`
	SellPrice2       float64    `db:"sell_price2" json:"sell_price2"`
	SellPrice3       float64    `db:"sell_price3" json:"sell_price3"`
	SellPrice4       *float64   `db:"sell_price4" json:"sell_price4"`
	SellPrice5       *float64   `db:"sell_price5" json:"sell_price5"`
	UpdatedByName    *string    `db:"updated_by_name" json:"updated_by_name"`
	UpdatedAt        *time.Time `db:"updated_at,omitempty" json:"updated_at"`
	DistPriceIdOld   *int64     `db:"dist_price_id_old" json:"dist_price_id_old"`
	Status           int        `db:"status" json:"status"`
}

type DistPriceLookup struct {
	CustId           string     `db:"cust_id" json:"cust_id"`
	DistPriceId      int64      `db:"dist_price_id" json:"dist_price_id"`
	DistPriceGroupId int64      `db:"dist_price_group_id" json:"dist_price_group_id"`
	DistPriceGrpCode string     `db:"dist_price_grp_code" json:"dist_price_grp_code"`
	DistPriceGrpName string     `db:"dist_price_grp_name" json:"dist_price_grp_name"`
	StartDate        *time.Time `db:"start_date" json:"start_date"`
	EndDate          *time.Time `db:"end_date" json:"end_date"`
	ProId            int64      `db:"pro_id" json:"pro_id"`
	ProCode          string     `db:"pro_code" json:"pro_code"`
	ProName          string     `db:"pro_name" json:"pro_name"`
	SupId            int        `db:"sup_id" json:"sup_id"`
	SupCode          string     `db:"sup_code" json:"sup_code"`
	SupName          string     `db:"sup_name" json:"sup_name"`
	UnitId1          string     `db:"unit_id1" json:"unit_id1"`
	UnitId2          string     `db:"unit_id2" json:"unit_id2"`
	UnitId3          string     `db:"unit_id3" json:"unit_id3"`
	UnitId4          *string    `db:"unit_id4" json:"unit_id4"`
	UnitId5          *string    `db:"unit_id5" json:"unit_id5"`
	UnitName1        *string    `db:"unit_name1" json:"unit_name1"`
	UnitName2        *string    `db:"unit_name2" json:"unit_name2"`
	UnitName3        *string    `db:"unit_name3" json:"unit_name3"`
	UnitName4        *string    `db:"unit_name4" json:"unit_name4"`
	UnitName5        *string    `db:"unit_name5" json:"unit_name5"`
	ConvUnit2        float32    `db:"conv_unit2" json:"conv_unit2"`
	ConvUnit3        float32    `db:"conv_unit3" json:"conv_unit3"`
	ConvUnit4        float32    `db:"conv_unit4" json:"conv_unit4"`
	ConvUnit5        float32    `db:"conv_unit5" json:"conv_unit5"`
	PurchPrice1      float64    `db:"purch_price1" json:"purch_price1"`
	PurchPrice2      float64    `db:"purch_price2" json:"purch_price2"`
	PurchPrice3      float64    `db:"purch_price3" json:"purch_price3"`
	PurchPrice4      *float64   `db:"purch_price4" json:"purch_price4"`
	PurchPrice5      *float64   `db:"purch_price5" json:"purch_price5"`
	SellPrice1       float64    `db:"sell_price1" json:"sell_price1"`
	SellPrice2       float64    `db:"sell_price2" json:"sell_price2"`
	SellPrice3       float64    `db:"sell_price3" json:"sell_price3"`
	SellPrice4       *float64   `db:"sell_price4" json:"sell_price4"`
	SellPrice5       *float64   `db:"sell_price5" json:"sell_price5"`
	UpdatedByName    *string    `db:"updated_by_name" json:"updated_by_name"`
	UpdatedAt        *time.Time `db:"updated_at,omitempty" json:"updated_at"`
	DistPriceIdOld   *int64     `db:"dist_price_id_old" json:"dist_price_id_old"`
	Vat              *float64   `json:"vat" db:"vat"`
	VatBg            *float64   `json:"vat_bg" db:"vat_bg"`
	VatLgPurch       *float64   `json:"vat_lg_purch" db:"vat_lg_purch"`
	VatLgSell        *float64   `json:"vat_lg_sell" db:"vat_lg_sell"`
	ExciseRate       float64    `json:"excise_rate" db:"excise_rate"`
	ExciseTax        float64    `json:"excise_tax" db:"excise_tax"`
	Qty              float64    `db:"qty" json:"qty"`
	QtyOnShipping    float64    `db:"qty_on_shipping" json:"qty_on_shipping"`
	QtyOnOrder       float64    `db:"qty_on_order" json:"qty_on_order"`
	QtyBs            float64    `db:"qty_bs" json:"qty_bs"`
	QtyExp           float64    `db:"qty_exp" json:"qty_exp"`
}

type DistPriceLookupProduct struct {
	CustId           string     `db:"cust_id" json:"cust_id"`
	DistPriceId      int64      `db:"dist_price_id" json:"dist_price_id"`
	DistPriceGroupId int64      `db:"dist_price_group_id" json:"dist_price_group_id"`
	DistPriceGrpCode string     `db:"dist_price_grp_code" json:"dist_price_grp_code"`
	DistPriceGrpName string     `db:"dist_price_grp_name" json:"dist_price_grp_name"`
	StartDate        *time.Time `db:"start_date" json:"start_date"`
	ProId            int64      `db:"pro_id" json:"pro_id"`
	ProCode          string     `db:"pro_code" json:"pro_code"`
	ProName          string     `db:"pro_name" json:"pro_name"`
	UnitId1          string     `db:"unit_id1" json:"unit_id1"`
	UnitId2          string     `db:"unit_id2" json:"unit_id2"`
	UnitId3          string     `db:"unit_id3" json:"unit_id3"`
	UnitId4          *string    `db:"unit_id4" json:"unit_id4"`
	UnitId5          *string    `db:"unit_id5" json:"unit_id5"`
	UnitName1        *string    `db:"unit_name1" json:"unit_name1"`
	UnitName2        *string    `db:"unit_name2" json:"unit_name2"`
	UnitName3        *string    `db:"unit_name3" json:"unit_name3"`
	UnitName4        *string    `db:"unit_name4" json:"unit_name4"`
	UnitName5        *string    `db:"unit_name5" json:"unit_name5"`
	ConvUnit2        float32    `db:"conv_unit2" json:"conv_unit2"`
	ConvUnit3        float32    `db:"conv_unit3" json:"conv_unit3"`
	ConvUnit4        float32    `db:"conv_unit4" json:"conv_unit4"`
	ConvUnit5        float32    `db:"conv_unit5" json:"conv_unit5"`
	PurchPrice1      float64    `db:"purch_price1" json:"purch_price1"`
	PurchPrice2      float64    `db:"purch_price2" json:"purch_price2"`
	PurchPrice3      float64    `db:"purch_price3" json:"purch_price3"`
	PurchPrice4      *float64   `db:"purch_price4" json:"purch_price4"`
	PurchPrice5      *float64   `db:"purch_price5" json:"purch_price5"`
	SellPrice1       float64    `db:"sell_price1" json:"sell_price1"`
	SellPrice2       float64    `db:"sell_price2" json:"sell_price2"`
	SellPrice3       float64    `db:"sell_price3" json:"sell_price3"`
	SellPrice4       *float64   `db:"sell_price4" json:"sell_price4"`
	SellPrice5       *float64   `db:"sell_price5" json:"sell_price5"`
	DistPriceIdOld   *int64     `db:"dist_price_id_old" json:"dist_price_id_old"`
	Vat              *float64   `json:"vat" db:"vat"`
	VatBg            *float64   `json:"vat_bg" db:"vat_bg"`
	VatLgPurch       *float64   `json:"vat_lg_purch" db:"vat_lg_purch"`
	VatLgSell        *float64   `json:"vat_lg_sell" db:"vat_lg_sell"`
	ExciseRate       float64    `json:"excise_rate" db:"excise_rate"`
	ExciseTax        float64    `json:"excise_tax" db:"excise_tax"`
}
type DistPriceUpdate struct {
	DistPriceGroupId *int64     `sql:"dist_price_group_id" json:"dist_price_group_id"`
	StartDate        *string    `sql:"start_date" json:"start_date,omitempty"`
	EndDate          *string    `sql:"end_date" json:"end_date,omitempty"`
	ProId            *int64     `sql:"pro_id" json:"pro_id,omitempty"`
	UnitId1          *string    `sql:"unit_id1" json:"unit_id1,omitempty"`
	UnitId2          *string    `sql:"unit_id2" json:"unit_id2,omitempty"`
	UnitId3          *string    `sql:"unit_id3" json:"unit_id3,omitempty"`
	UnitId4          *string    `sql:"unit_id4" json:"unit_id4,omitempty"`
	UnitId5          *string    `sql:"unit_id5" json:"unit_id5,omitempty"`
	ConvUnit2        *float32   `sql:"conv_unit2" json:"conv_unit2,omitempty"`
	ConvUnit3        *float32   `sql:"conv_unit3" json:"conv_unit3,omitempty"`
	ConvUnit4        *float32   `sql:"conv_unit4" json:"conv_unit4,omitempty"`
	ConvUnit5        *float32   `sql:"conv_unit5" json:"conv_unit5,omitempty"`
	PurchPrice1      *float64   `sql:"purch_price1" json:"purch_price1,omitempty"`
	PurchPrice2      *float64   `sql:"purch_price2" json:"purch_price2,omitempty"`
	PurchPrice3      *float64   `sql:"purch_price3" json:"purch_price3,omitempty"`
	PurchPrice4      *float64   `sql:"purch_price4" json:"purch_price4,omitempty"`
	PurchPrice5      *float64   `sql:"purch_price5" json:"purch_price5,omitempty"`
	SellPrice1       *float64   `sql:"sell_price1" json:"sell_price1,omitempty"`
	SellPrice2       *float64   `sql:"sell_price2" json:"sell_price2,omitempty"`
	SellPrice3       *float64   `sql:"sell_price3" json:"sell_price3,omitempty"`
	SellPrice4       *float64   `sql:"sell_price4" json:"sell_price4,omitempty"`
	SellPrice5       *float64   `sql:"sell_price5" json:"sell_price5,omitempty"`
	UpdatedAt        *time.Time `sql:"updated_at" json:"updated_at"`
	UpdatedBy        *int64     `sql:"updated_by" json:"updated_by"`
	DistPriceIdOld   *int64     `sql:"dist_price_id_old" json:"dist_price_id_old,omitempty"`
}

type DistPricePublish struct {
	Status    *int       `sql:"status" json:"status"`
	UpdatedAt *time.Time `sql:"updated_at" json:"updated_at"`
}
